
== UnbalancedElectrical Profile Specification

// Settings:
:doctype: inline
:reproducible:
:icons: font
:sectnums:
:sectnumlevels: 4
:xrefstyle: short

Profile namespace: http://www.ucaiug.org/gmdm/electrical/unbalanced#

.UnbalancedElectrical Profile
plantuml::./Profiles/UnbalancedElectrical.rdfs-t2b.puml[format=svg, align=center]


=== Concrete Classes

[[UnbalancedElectrical-ACLineSegment]]
==== (Description) ACLineSegment

Inheritance path = <<UnbalancedElectrical-Conductor,Conductor>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-ACLineSegment,ACLineSegment>>.
endif::UnbalancedElectrical-description-profile[]

:ACLineSegment:
A line segment is a conductor or combination of conductors, with consistent electrical characteristics along its length, building a single electrical system that carries alternating current between two points in the power system.

The BaseVoltage at the two ends of a line segment shall have the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly different BaseVoltage.nominalVoltages and variation is allowed. Larger voltage difference in general requires use of an equivalent branch.

Line segment impedances can be either directly described in electrical terms or physical line detail can be provided from which impedances can be calculated.

{lt}b{gt}Directly described impedances{lt}/b{gt}

For symmetrical, transposed three phase line segments, it is sufficient to use attributes of the line segment, which describe impedances and admittances for the entire length of the line segment. Additionally, line segment impedances can be computed by using line segment length and associated per length impedances.

Unbalanced modeling of impedances is supported by the per length phase impedance matrix (PerLengthPhaseImpedance) in conjunction with phase-to-sequence number mapping supplied by either ACLineSegmentPhase or WirePosition. The sequence numbers are referenced by the row and column attributes of the per length phase impedance matrix. This method enables single-phase and two-phase line segments, and transpositions of phases, to be described using the same per length phase impedance matrix. The length of the line segment is used in the computation of total impedance values for the line segment.

{lt}b{gt}Line detail characteristics{lt}/b{gt}

There are three approaches to providing line detail and all use WireAssembly to supply line positions:

{lt}ul{gt}

{lt}li{gt}Option 1 - WireAssembly supplies only line positions. ACLineSegmentPhase points to wire type and intraphase spacing and supplies the phase-to-sequence number mapping.{lt}/li{gt}

{lt}li{gt}Option 2 - WireAssembly supplies line position and, for each position, also supplies wire type and intraphase spacing. ACLineSegmentPhase supplies the phase-to-sequence number mapping.{lt}/li{gt}

{lt}li{gt}Option 3 - WireAssembly supplies line position and, for each position, also supplies wire type and intraphase spacing and phase. WireAssembly therefore supplies the phase-to-sequence number mapping and ACLineSegmentPhase is not needed.{lt}/li{gt}

{lt}/ul{gt}


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|PerLengthImpedance
|1..1
|<<UnbalancedElectrical-PerLengthImpedance,PerLengthImpedance>>
|
Per-length impedance of this line segment.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|length
|1..1
|<<UnbalancedElectrical-Length,Length>>
|see <<UnbalancedElectrical-Conductor,Conductor>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ACLineSegment:

[[UnbalancedElectrical-ACLineSegmentPhase]]
==== (Description) ACLineSegmentPhase

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-ACLineSegmentPhase,ACLineSegmentPhase>>.
endif::UnbalancedElectrical-description-profile[]

:ACLineSegmentPhase:
A line segment phase represents one phase (or optionally the neutral) of an alternating current line segment.

Under most circumstances there is not a line segment phase for the neutral. However, if a wire assembly is being used and it does not specify phase, a line segment phase must exist for each position in the assembly (including the neutral).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|sequenceNumber
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
Sequence number provides the numbering for this line segment phase. When impedance is directly described, sequence number binds the phase to the column and row for entries in the per length phase impedance matrix (PhaseImpedanceData of PerLengthPhaseImpedance). When used in conjunction with a wire assembly description, sequence number associates the line segment phase to a position.

For a line segment not a part of a parallel line segment group, sequence number starts at one and increments by one through each line segment phase associated with the line segment. If there is a line segment phase for neutral, it is numbered last.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ACLineSegmentPhase:

[[UnbalancedElectrical-AsynchronousMachine]]
==== (Description) AsynchronousMachine

Inheritance path = <<UnbalancedElectrical-RotatingMachine,RotatingMachine>> => <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-AsynchronousMachine,AsynchronousMachine>>.
endif::UnbalancedElectrical-description-profile[]

:AsynchronousMachine:
A rotating machine whose shaft rotates asynchronously with the electrical field. Also known as an induction machine with no external connection to the rotor windings, e.g. squirrel-cage induction machine.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|see <<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|ratedU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|see <<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!AsynchronousMachine:

[[UnbalancedElectrical-BatteryUnit]]
==== BatteryUnit

Inheritance path = <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:BatteryUnit:
An electrochemical energy storage device.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedE
|0..1
|<<UnbalancedElectrical-RealEnergy,RealEnergy>>
|
Full energy storage capacity of the battery. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|0..1
|<<UnbalancedElectrical-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!BatteryUnit:

[[UnbalancedElectrical-Breaker]]
==== (Description) Breaker

Inheritance path = <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>> => <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Breaker,Breaker>>.
endif::UnbalancedElectrical-description-profile[]

:Breaker:
A mechanical switching device capable of making, carrying, and breaking currents under normal circuit conditions and also making, carrying for a specified time, and breaking currents under specified abnormal circuit conditions e.g. those of short circuit.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>>
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Breaker:

[[UnbalancedElectrical-Disconnector]]
==== (Description) Disconnector

Inheritance path = <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Disconnector,Disconnector>>.
endif::UnbalancedElectrical-description-profile[]

:Disconnector:
A mechanical switching device which provides, in the open position, an isolating distance in accordance with specified requirements.

A disconnector is capable of opening and closing a circuit when either negligible current is broken or made, or when no significant change in the voltage across the terminals of each of the poles of the disconnector occurs. It is also capable of carrying currents under normal circuit conditions and carrying for a specified time currents under abnormal conditions such as those of short circuit.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Disconnector:

[[UnbalancedElectrical-EnergyConsumer]]
==== (Description) EnergyConsumer

Inheritance path = <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-EnergyConsumer,EnergyConsumer>>.
endif::UnbalancedElectrical-description-profile[]

:EnergyConsumer:
Generic user of energy - a point of consumption on the power system model.

EnergyConsumer.pfixed, .qfixed, .pfixedPct and .qfixedPct have meaning only if there is no LoadResponseCharacteristic associated with EnergyConsumer or if LoadResponseCharacteristic.exponentModel is set to False.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|LoadResponse
|0..1
|<<UnbalancedElectrical-LoadResponseCharacteristic,LoadResponseCharacteristic>>
|
The load response characteristic of this load. If missing, this load is assumed to be constant power.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!EnergyConsumer:

[[UnbalancedElectrical-EnergySource]]
==== (Description) EnergySource

Inheritance path = <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-EnergySource,EnergySource>>.
endif::UnbalancedElectrical-description-profile[]

:EnergySource:
A generic equivalent for an energy supplier on a transmission or distribution voltage level.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|nominalVoltage
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Phase-to-phase nominal voltage.

|r
|1..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Positive sequence Thevenin resistance.

|x
|1..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Positive sequence Thevenin reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!EnergySource:

[[UnbalancedElectrical-FossilFuel]]
==== FossilFuel

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:FossilFuel:
The fossil fuel consumed by the non-nuclear thermal generating unit. For example, coal, oil, gas, etc. These are the specific fuels that the generating unit can consume.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!FossilFuel:

[[UnbalancedElectrical-Fuse]]
==== (Description) Fuse

Inheritance path = <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Fuse,Fuse>>.
endif::UnbalancedElectrical-description-profile[]

:Fuse:
An overcurrent protective device with a circuit opening fusible part that is heated and severed by the passage of overcurrent through it. A fuse is considered a switching device because it breaks current.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Fuse:

[[UnbalancedElectrical-LinearShuntCompensator]]
==== (Description) LinearShuntCompensator

Inheritance path = <<UnbalancedElectrical-ShuntCompensator,ShuntCompensator>> => <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-LinearShuntCompensator,LinearShuntCompensator>>.
endif::UnbalancedElectrical-description-profile[]

:LinearShuntCompensator:
A linear shunt compensator has banks or sections with equal admittance values.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|bPerSection
|1..1
|<<UnbalancedElectrical-Susceptance,Susceptance>>
|
Positive sequence shunt (charging) susceptance per section.

|gPerSection
|1..1
|<<UnbalancedElectrical-Conductance,Conductance>>
|
Positive sequence shunt (charging) conductance per section.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aVRDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|see <<UnbalancedElectrical-ShuntCompensator,ShuntCompensator>>
|maximumSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-ShuntCompensator,ShuntCompensator>>
|nomU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|see <<UnbalancedElectrical-ShuntCompensator,ShuntCompensator>>
|normalSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-ShuntCompensator,ShuntCompensator>>
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!LinearShuntCompensator:

[[UnbalancedElectrical-LinearShuntCompensatorPhase]]
==== (Description) LinearShuntCompensatorPhase

Inheritance path = <<UnbalancedElectrical-ShuntCompensatorPhase,ShuntCompensatorPhase>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-LinearShuntCompensatorPhase,LinearShuntCompensatorPhase>>.
endif::UnbalancedElectrical-description-profile[]

:LinearShuntCompensatorPhase:
A per phase linear shunt compensator has banks or sections with equal admittance values.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|bPerSection
|1..1
|<<UnbalancedElectrical-Susceptance,Susceptance>>
|
Susceptance per section of the phase if shunt compensator is wye connected. Susceptance per section phase to phase if shunt compensator is delta connected.

|gPerSection
|1..1
|<<UnbalancedElectrical-Conductance,Conductance>>
|
Conductance per section for this phase if shunt compensator is wye connected. Conductance per section phase to phase if shunt compensator is delta connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maximumSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|normalSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!LinearShuntCompensatorPhase:

[[UnbalancedElectrical-LoadBreakSwitch]]
==== (Description) LoadBreakSwitch

Inheritance path = <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>> => <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-LoadBreakSwitch,LoadBreakSwitch>>.
endif::UnbalancedElectrical-description-profile[]

:LoadBreakSwitch:
A mechanical switching device capable of making, carrying, and breaking currents under normal operating conditions.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>>
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!LoadBreakSwitch:

[[UnbalancedElectrical-LoadResponseCharacteristic]]
==== LoadResponseCharacteristic

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:LoadResponseCharacteristic:
Models the characteristic response of the load demand due to changes in system conditions such as voltage and frequency. It is not related to demand response.

If LoadResponseCharacteristic.exponentModel is True, the exponential voltage or frequency dependent models are specified and used as to calculate active and reactive power components of the load model.

The equations to calculate active and reactive power components of the load model are internal to the power flow calculation, hence they use different quantities depending on the use case of the data exchange.

The equations for exponential voltage dependent load model injected power are:

pInjection= Pnominal{asterisk} (Voltage/cim:BaseVoltage.nominalVoltage) {asterisk}{asterisk} cim:LoadResponseCharacteristic.pVoltageExponent

qInjection= Qnominal{asterisk} (Voltage/cim:BaseVoltage.nominalVoltage) {asterisk}{asterisk} cim:LoadResponseCharacteristic.qVoltageExponent

pInjection = Pnominal{asterisk} (Frequency/(Nominal frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pFrequencyExponent

qInjection = Qnominal{asterisk} (Frequency/(Nominal frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qFrequencyExponent

Note that both voltage and frequency exponents could be used together so the full equation would be:

pInjection = Pnominal{asterisk} (Voltage/(cim:BaseVoltage.nominalVoltage)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pVoltageExponent {asterisk} (Frequency/(base frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pFrequencyExponent

qInjection = Qnominal{asterisk} (Voltage/(cim:BaseVoltage.nominalVoltage)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qVoltageExponent {asterisk} (Frequency/(base frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qFrequencyExponent

The voltage and frequency expressed in the equation are values obtained from solved power flow. Base voltage and base frequency are those derived from the connectivity of the static network model.

Where:

1) {asterisk} means "multiply" and {asterisk}{asterisk} is "raised to the power of";

2) Pnominal and Qnominal represent the active power and reactive power at nominal voltage as any load described by the voltage exponential model shall be given at nominal voltage. This means that EnergyConsumer.p and EnergyConsumer.q are at nominal voltage.

3) After power flow is solved:

-pInjection and qInjection correspond to SvPowerflow.p and SvPowerflow.q respectively.

- Voltage corresponds to SvVoltage.v at the TopologicalNode where the load is connected.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|exponentModel
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
Indicates the exponential voltage dependency model is to be used. If false, the coefficient model is to be used.

The exponential voltage dependency model consist of the attributes:

- pVoltageExponent

- qVoltageExponent

- pFrequencyExponent

- qFrequencyExponent.

The coefficient model consist of the attributes:

- pConstantImpedance

- pConstantCurrent

- pConstantPower

- qConstantImpedance

- qConstantCurrent

- qConstantPower.

The sum of pConstantImpedance, pConstantCurrent and pConstantPower shall equal 1.

The sum of qConstantImpedance, qConstantCurrent and qConstantPower shall equal 1.

|pConstantCurrent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of active power load modelled as constant current.

|pConstantImpedance
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of active power load modelled as constant impedance.

|pConstantPower
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of active power load modelled as constant power.

|pFrequencyExponent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Exponent of per unit frequency effecting active power.

|pVoltageExponent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Exponent of per unit voltage effecting real power.

|qConstantCurrent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of reactive power load modelled as constant current.

|qConstantImpedance
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of reactive power load modelled as constant impedance.

|qConstantPower
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Portion of reactive power load modelled as constant power.

|qFrequencyExponent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Exponent of per unit frequency effecting reactive power.

|qVoltageExponent
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Exponent of per unit voltage effecting reactive power.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!LoadResponseCharacteristic:

[[UnbalancedElectrical-PerLengthPhaseImpedance]]
==== PerLengthPhaseImpedance

Inheritance path = <<UnbalancedElectrical-PerLengthImpedance,PerLengthImpedance>> => <<UnbalancedElectrical-PerLengthLineParameter,PerLengthLineParameter>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PerLengthPhaseImpedance:
The per length phase impedance matrix expresses impedance and admittance parameters per unit length for n-conductor unbalanced line segments. A phase impedance matrix contains both self impedances for each phase and mutual impedances between pairs of phases. The matrix is stored in symmetric lower triangular format where the diagonal entries represent self-impedances (and have the same value in row and column) and the off diagonal entries represent phase-to-phase impedances (and have different row and column values).

The matrix can be use to express impedances for both non-coupled and coupled line segments. Coupled line segments share a single per length phase impedance matrix whose entries reflect the self and mutual impedances of all the phases of all the wires.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|conductorCount
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
Conductor count identifies the number of phase, neutral, and other wires represented in the phase impedance matrix and constrains the number of elements in the matrix. Typically, Kron reduction is used for incorporating effects of neutral impedance in the phase conductor values (so conductor count only considers phase wires), but neutrals can be included in the matrix (in which case conductor count would include the neutral wire(s)). For a phase impedance matrix associated with the lines of a coupled line segment group, the conductor count reflects the total of the conductors associated with all the coupled line segments in the group.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PerLengthPhaseImpedance:

[[UnbalancedElectrical-PhaseImpedanceData]]
==== PhaseImpedanceData

Inheritance path = <<UnbalancedElectrical-Identity,Identity>>

:PhaseImpedanceData:
Per length phase impedance matrix entry describes impedance and conductance matrix element values for a specific row and column of the matrix.

The phases to which each entry applies can be determined by means of the row and column attributes which bind to a sequence number provided in either ACLineSegmentPhase or WirePosition (which also specify phase). Due to physical symmetry that is reflected in the matrix, only the lower triangle of the matrix is populated with the row and column method. That is, the column attribute is always less than or equal to the row attribute.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|1..1
|<<UnbalancedElectrical-SusceptancePerLength,SusceptancePerLength>>
|
Susceptance matrix entry value, per length of unit.

|column
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The matrix entry's column number has a range of possible values from 1 to the conductor count of the matrix, but due to symmetry, only entries in the lower triangle (including diagonal) of the matrix need be defined. Column number binds to the sequence number in either ACLineSegmentPhase or WirePosition, which then identifies the phase for this entry.

|r
|1..1
|<<UnbalancedElectrical-ResistancePerLength,ResistancePerLength>>
|
Resistance matrix entry value, per length of unit.

|row
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The matrix entry's row number has a range of possible values from 1 to the conductor count of the matrix, but due to symmetry, only entries in the lower triangle (including diagonal) of the matrix need be defined. Row number binds to the sequence number in either ACLineSegmentPhase or WirePosition, which then identifies the phase for this entry.

|x
|1..1
|<<UnbalancedElectrical-ReactancePerLength,ReactancePerLength>>
|
Reactance matrix entry value, per length of unit.

|PhaseImpedance
|0..1
|<<UnbalancedElectrical-PerLengthPhaseImpedance,PerLengthPhaseImpedance>>
|
Conductor phase impedance to which this data belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PhaseImpedanceData:

[[UnbalancedElectrical-PhotoVoltaicUnit]]
==== PhotoVoltaicUnit

Inheritance path = <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PhotoVoltaicUnit:
A photovoltaic device or an aggregation of such devices.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|0..1
|<<UnbalancedElectrical-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PhotoVoltaicUnit:

[[UnbalancedElectrical-PowerElectronicsConnection]]
==== (Description) PowerElectronicsConnection

Inheritance path = <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-PowerElectronicsConnection,PowerElectronicsConnection>>.
endif::UnbalancedElectrical-description-profile[]

:PowerElectronicsConnection:
A connection to the AC network for energy production or consumption that uses power electronics rather than rotating machines.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#controlMode (gmdm, enumeration)#
|0..1
|<<UnbalancedElectrical-ConverterControlModeKind,ConverterControlModeKind>>
|
Inverter control mode indicating whether reactive power output is based on constant PF or constant Q

|maxQ
|0..1
|<<UnbalancedElectrical-ReactivePower,ReactivePower>>
|
Maximum reactive power limit. This is the maximum (nameplate) limit for the unit.

|minQ
|0..1
|<<UnbalancedElectrical-ReactivePower,ReactivePower>>
|
Minimum reactive power limit for the unit. This is the minimum (nameplate) limit for the unit.

|ratedS
|0..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|
Nameplate apparent power rating for the unit.

The attribute shall have a positive value.

|ratedU
|0..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Rated voltage (nameplate data, Ur in IEC 60909-0). It is primarily used for short circuit data exchange according to IEC 60909.

The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerElectronicsConnection:

[[UnbalancedElectrical-PowerElectronicsThermalUnit]]
==== PowerElectronicsThermalUnit

Inheritance path = <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PowerElectronicsThermalUnit:
A thermal unit that is connected via an inverter such as through a back-to-back converter


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#FossilFuels#
|0..1
|<<UnbalancedElectrical-FossilFuel,FossilFuel>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|0..1
|<<UnbalancedElectrical-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerElectronicsThermalUnit:

[[UnbalancedElectrical-PowerElectronicsWindUnit]]
==== PowerElectronicsWindUnit

Inheritance path = <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PowerElectronicsWindUnit:
A wind generating unit that connects to the AC network with power electronics rather than rotating machines or an aggregation of such units.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|0..1
|<<UnbalancedElectrical-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<UnbalancedElectrical-PowerElectronicsUnit,PowerElectronicsUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerElectronicsWindUnit:

[[UnbalancedElectrical-PowerTransformer]]
==== (Description) PowerTransformer

Inheritance path = <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-PowerTransformer,PowerTransformer>>.
endif::UnbalancedElectrical-description-profile[]

:PowerTransformer:
An electrical device consisting of two or more coupled windings, with or without a magnetic core, for introducing mutual coupling between electric circuits. Transformers can be used to control voltage and phase shift (active power flow).

A power transformer may be composed of separate transformer tanks that need not be identical.

A power transformer can be modelled with or without tanks and is intended for use in both balanced and unbalanced representations. A power transformer typically has two terminals, but may have one (grounding), three or more terminals.

The inherited association ConductingEquipment.BaseVoltage should not be used. The association from TransformerEnd to BaseVoltage should be used instead.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerTransformer:

[[UnbalancedElectrical-PowerTransformerEnd]]
==== (Description) PowerTransformerEnd

Inheritance path = <<UnbalancedElectrical-TransformerEnd,TransformerEnd>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-PowerTransformerEnd,PowerTransformerEnd>>.
endif::UnbalancedElectrical-description-profile[]

:PowerTransformerEnd:
A PowerTransformerEnd is associated with each Terminal of a PowerTransformer.

The impedance values r, r0, x, and x0 of a PowerTransformerEnd represents a star equivalent as follows.

1) two PowerTransformerEnd-s shall be defined for a two Terminal PowerTransformer even if the two PowerTransformerEnd-s have the same rated voltage. The high voltage PowerTransformerEnd (TransformerEnd.endNumber=1) is the one used to exchange resistances (r, r0) and reactances (x, x0) of the PowerTransformer while the low voltage PowerTransformerEnd (TransformerEnd.endNumber=2) shall have zero impedance values.

2) for a three Terminal PowerTransformer the three PowerTransformerEnds represent a star equivalent with each leg in the star represented by r, r0, x, and x0 values.

3) For a three Terminal transformer each PowerTransformerEnd shall have g, g0, b and b0 values corresponding to the no load losses distributed on the three PowerTransformerEnds. The total no load loss shunt impedances may also be placed at one of the PowerTransformerEnds, preferably the end numbered 1, having the shunt values on end 1. This is the preferred way.

4) for a PowerTransformer with more than three Terminals the PowerTransformerEnd impedance values cannot be used. Instead use the TransformerMeshImpedance or split the transformer into multiple PowerTransformers.

Each PowerTransformerEnd must be contained by a PowerTransformer. Because a PowerTransformerEnd (or any other object) can not be contained by more than one parent, a PowerTransformerEnd can not have an association to an EquipmentContainer (Substation, VoltageLevel, etc).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|0..1
|<<UnbalancedElectrical-Susceptance,Susceptance>>
|
Magnetizing branch susceptance (B mag). The value can be positive or negative.

|g
|0..1
|<<UnbalancedElectrical-Conductance,Conductance>>
|
Magnetizing branch conductance.

|phaseAngleClock
|0..1
|<<UnbalancedElectrical-Integer,Integer>>
|
Terminal voltage phase angle displacement where 360 degrees are represented with clock hours. The valid values are 0 to 11. For example, for the secondary side end of a transformer with vector group code of 'Dyn11', specify the connection kind as wye with neutral and specify the phase angle of the clock as 11. The clock value of the transformer end number specified as 1, is assumed to be zero. Note the transformer end number is not assumed to be the same as the terminal sequence number.

|r
|1..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Resistance (star-model) of the transformer end.

The attribute shall be equal to or greater than zero for non-equivalent transformers.

|ratedS
|1..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|
Normal apparent power rating.

The attribute shall be a positive value. For a two-winding transformer the values for the high and low voltage sides shall be identical.

|ratedU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Rated voltage: phase-phase for three-phase windings, and either phase-phase or phase-neutral for single-phase windings.

A high voltage side, as given by TransformerEnd.endNumber, shall have a ratedU that is greater than or equal to ratedU for the lower voltage sides.

The attribute shall be a positive value.

|x
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Positive sequence series reactance (star-model) of the transformer end.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|grounded
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|rground
|0..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|xground
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|CoreAdmittance
|0..1
|<<UnbalancedElectrical-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerTransformerEnd:

[[UnbalancedElectrical-RatioTapChanger]]
==== RatioTapChanger

Inheritance path = <<UnbalancedElectrical-TapChanger,TapChanger>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:RatioTapChanger:
A tap changer that changes the voltage ratio impacting the voltage magnitude but not the phase angle across the transformer.

Angle sign convention (general): Positive value indicates a positive phase shift from the winding where the tap is located to the other winding (for a two-winding transformer).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|stepVoltageIncrement
|0..1
|<<UnbalancedElectrical-PerCent,PerCent>>
|
Tap step increment, in per cent of rated voltage of the power transformer end, per step position.

When the increment is negative, the voltage decreases when the tap step increases.

|TransformerEnd
|1..1
|<<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|
Transformer end to which this ratio tap changer belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|controlEnabled
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|[extension]#ctRating (gmdm)#
|0..1
|<<UnbalancedElectrical-Float,Float>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|ctRatio
|0..1
|<<UnbalancedElectrical-Float,Float>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|highStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|initialDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|lowStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|ltcFlag
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|neutralStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|neutralU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|ptRatio
|0..1
|<<UnbalancedElectrical-Float,Float>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|subsequentDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|TapChangerControl
|0..1
|<<UnbalancedElectrical-TapChangerControl,TapChangerControl>>
|see <<UnbalancedElectrical-TapChanger,TapChanger>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!RatioTapChanger:

[[UnbalancedElectrical-Recloser]]
==== (Description) Recloser

Inheritance path = <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>> => <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Recloser,Recloser>>.
endif::UnbalancedElectrical-description-profile[]

:Recloser:
Pole-mounted fault interrupter with built-in phase and ground relays, current transformer (CT), and supplemental controls.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-ProtectedSwitch,ProtectedSwitch>>
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Recloser:

[[UnbalancedElectrical-Sectionaliser]]
==== (Description) Sectionaliser

Inheritance path = <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Sectionaliser,Sectionaliser>>.
endif::UnbalancedElectrical-description-profile[]

:Sectionaliser:
Automatic switch that will lock open to isolate a faulted section. It may, or may not, have load breaking capability. Its primary purpose is to provide fault sectionalising at locations where the fault current is either too high, or too low, for proper coordination of fuses.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Sectionaliser:

[[UnbalancedElectrical-SeriesCompensator]]
==== (Description) SeriesCompensator

Inheritance path = <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-SeriesCompensator,SeriesCompensator>>.
endif::UnbalancedElectrical-description-profile[]

:SeriesCompensator:
A Series Compensator is a series capacitor or reactor or an AC transmission line without charging susceptance. It is a two terminal device.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|r
|1..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Positive sequence resistance.

|x
|1..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Positive sequence reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!SeriesCompensator:

[[UnbalancedElectrical-SynchronousMachine]]
==== (Description) SynchronousMachine

Inheritance path = <<UnbalancedElectrical-RotatingMachine,RotatingMachine>> => <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-SynchronousMachine,SynchronousMachine>>.
endif::UnbalancedElectrical-description-profile[]

:SynchronousMachine:
An electromechanical device that operates with shaft rotating synchronously with the network. It is a single machine operating either as a generator or synchronous condenser or pump.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|see <<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|ratedU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|see <<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!SynchronousMachine:

[[UnbalancedElectrical-TapChangerControl]]
==== TapChangerControl

Inheritance path = <<UnbalancedElectrical-RegulatingControl,RegulatingControl>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:TapChangerControl:
Describes behaviour specific to tap changers, e.g. how the voltage at the end of a line varies with the load level and compensation of the voltage drop by tap adjustment. When TapChanger.ctRatio and .ptRatio are present, RegulatingControl.targetVoltage RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue, RegulatingControl.minAllowedTargetValue as well as TapChangerControl.maxLimitVoltage and TapChangerControl.minLimitVoltage shall be expressed in terms of secondary CT currents and PT voltages.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|lineDropCompensation
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
If true, the line drop compensation is to be applied.

|lineDropR
|0..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Line drop compensator resistance setting for normal (forward) power flow.

|lineDropX
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Line drop compensator reactance setting for normal (forward) power flow.

|maxLimitVoltage
|0..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Maximum allowed regulated voltage on the PT secondary. This is the locally measured secondary voltage, including the effect of any line drop compensation. Typically used for distribution circuit voltage regulator. Sometimes referred to as first-house protection. If utilized, then TapChanger.ptRatio must be supplied.

|minLimitVoltage
|0..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Minimum allowed regulated voltage on the PT secondary. This is the locally measured secondary voltage, including the effect of any line drop compensation. Typically used for distribution circuit voltage regulator. Sometimes referred to as last-house protection. If utilized, then TapChanger.ptRatio must be supplied.

|reverseLineDropR
|0..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Line drop compensator resistance setting for reverse power flow.

|reverseLineDropX
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Line drop compensator reactance setting for reverse power flow.

|[extension]#reverseTargetDeadband (gmdm)#
|0..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
|[extension]#reverseTargetValue (gmdm)#
|0..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
|[extension]#reverseToNeutral (gmdm)#
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
|[extension]#reversible (gmdm)#
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
|[extension]#reversingDelay (gmdm)#
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|
|[extension]#reversingPowerThreshold (gmdm)#
|0..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|discrete
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|enabled
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|mode (enumeration)
|0..1
|<<UnbalancedElectrical-RegulatingControlModeKind,RegulatingControlModeKind>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|monitoredPhase (enumeration)
|0..1
|<<UnbalancedElectrical-PhaseCode,PhaseCode>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|targetDeadband
|0..1
|<<UnbalancedElectrical-Float,Float>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|targetValue
|0..1
|<<UnbalancedElectrical-Float,Float>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|Terminal
|1..1
|<<UnbalancedElectrical-Terminal,Terminal>>
|see <<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TapChangerControl:

[[UnbalancedElectrical-Terminal]]
==== (Description) Terminal

Inheritance path = <<UnbalancedElectrical-ACDCTerminal,ACDCTerminal>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-Terminal,Terminal>>.
endif::UnbalancedElectrical-description-profile[]

:Terminal:
An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Terminal:

[[UnbalancedElectrical-ThermalGeneratingUnit]]
==== ThermalGeneratingUnit

Inheritance path = <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ThermalGeneratingUnit:
A generating unit whose prime mover could be a steam turbine, combustion turbine, or diesel engine.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|FossilFuels
|0..*
|<<UnbalancedElectrical-FossilFuel,FossilFuel>>
|
A thermal generating unit may have one or more fossil fuels.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>>
|RotatingMachine
|1..1
|<<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|see <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ThermalGeneratingUnit:

[[UnbalancedElectrical-TransformerCoreAdmittance]]
==== TransformerCoreAdmittance

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:TransformerCoreAdmittance:
The transformer core admittance. Used to specify the core admittance of a transformer in a manner that can be shared among power transformers.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|1..1
|<<UnbalancedElectrical-Susceptance,Susceptance>>
|
Magnetizing branch susceptance (B mag). The value can be positive or negative.

|g
|1..1
|<<UnbalancedElectrical-Conductance,Conductance>>
|
Magnetizing branch conductance (G mag).

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TransformerCoreAdmittance:

[[UnbalancedElectrical-TransformerMeshImpedance]]
==== TransformerMeshImpedance

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:TransformerMeshImpedance:
Transformer mesh impedance (Delta-model) between transformer ends.

The typical case is that this class describes the impedance between two transformer ends pair-wise, i.e. the cardinalities at both transformer end associations are 1. However, in cases where two or more transformer ends are modelled the cardinalities are larger than 1.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|r
|1..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Resistance between the 'from' and the 'to' end, seen from the 'from' end.

|x
|1..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Reactance between the 'from' and the 'to' end, seen from the 'from' end.

|FromTransformerEnd
|0..1
|<<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|
From end this mesh impedance is connected to. It determines the voltage reference.

|ToTransformerEnd
|0..*
|<<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|
All transformer ends this mesh impedance is connected to.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TransformerMeshImpedance:

[[UnbalancedElectrical-TransformerTankEnd]]
==== (Description) TransformerTankEnd

Inheritance path = <<UnbalancedElectrical-TransformerEnd,TransformerEnd>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

ifdef::UnbalancedElectrical-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UnbalancedElectrical-description-profile}-TransformerTankEnd,TransformerTankEnd>>.
endif::UnbalancedElectrical-description-profile[]

:TransformerTankEnd:
Transformer tank end represents an individual winding for unbalanced models or for transformer tanks connected into a bank (and bank is modelled with the PowerTransformer).


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|grounded
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|rground
|0..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|xground
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|CoreAdmittance
|0..1
|<<UnbalancedElectrical-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|see <<UnbalancedElectrical-TransformerEnd,TransformerEnd>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TransformerTankEnd:

[[UnbalancedElectrical-WindGeneratingUnit]]
==== WindGeneratingUnit

Inheritance path = <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:WindGeneratingUnit:
A wind driven generating unit, connected to the grid by means of a rotating machine. May be used to represent a single turbine or an aggregation.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|windGenUnitType (enumeration)
|0..1
|<<UnbalancedElectrical-WindGenUnitKind,WindGenUnitKind>>
|
The kind of wind generating unit.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|see <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>>
|RotatingMachine
|1..1
|<<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|see <<UnbalancedElectrical-GeneratingUnit,GeneratingUnit>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!WindGeneratingUnit:


=== Abstract Classes

[[UnbalancedElectrical-ACDCTerminal]]
==== ACDCTerminal

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ACDCTerminal:
An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ACDCTerminal:

[[UnbalancedElectrical-ConductingEquipment]]
==== ConductingEquipment

Inheritance path = <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ConductingEquipment:
The parts of the AC power system that are designed to carry current or that are conductively connected through terminals.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ConductingEquipment:

[[UnbalancedElectrical-Conductor]]
==== Conductor

Inheritance path = <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:Conductor:
Combination of conducting material with consistent electrical characteristics, building a single electrical system, used to carry current between points in the power system.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|length
|1..1
|<<UnbalancedElectrical-Length,Length>>
|
Segment length for calculating line segment capabilities.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Conductor:

[[UnbalancedElectrical-ConnectivityNodeContainer]]
==== ConnectivityNodeContainer

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ConnectivityNodeContainer:
A base class for all objects that may contain connectivity nodes or topological nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ConnectivityNodeContainer:

[[UnbalancedElectrical-EnergyConnection]]
==== EnergyConnection

Inheritance path = <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:EnergyConnection:
A connection of energy generation or consumption on the power system model.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!EnergyConnection:

[[UnbalancedElectrical-Equipment]]
==== Equipment

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:Equipment:
The parts of a power system that are physical devices, electronic or mechanical.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Equipment:

[[UnbalancedElectrical-GeneratingUnit]]
==== GeneratingUnit

Inheritance path = <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:GeneratingUnit:
A single or set of synchronous machines for converting mechanical power into alternating-current power. For example, individual machines within a set may be defined for scheduling purposes while a single control signal is derived for the set. In this case there would be a GeneratingUnit for each member of the set and an additional GeneratingUnit corresponding to the set.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|
The unit's gross rated maximum capacity (book value).

The attribute shall be a positive value.

|RotatingMachine
|1..1
|<<UnbalancedElectrical-RotatingMachine,RotatingMachine>>
|
A synchronous machine may operate as a generator and as such becomes a member of a generating unit.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!GeneratingUnit:

[[UnbalancedElectrical-IdentifiedObject]]
==== IdentifiedObject

Inheritance path = <<UnbalancedElectrical-Identity,Identity>>

:IdentifiedObject:
This is a class that provides common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|
The description is a free human readable text describing or naming the object. It may be non unique and may not correlate to a naming hierarchy.

|name
|0..1
|<<UnbalancedElectrical-String,String>>
|
The name is any free human readable and possibly non unique text naming the object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!IdentifiedObject:

[[UnbalancedElectrical-Identity]]
==== Identity


:Identity:
This is a root class to provide common identification for all classes. IdentifiedObject and any class to be exchanged with RDF XML now inherits from Identity. mRID is superseded by Identity.identifier, which is typed to be a UUID.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|
A universally unique object identifier. Used to uniquely identify persistent objects between CIM messages.

|===
:!Identity:

[[UnbalancedElectrical-PerLengthImpedance]]
==== PerLengthImpedance

Inheritance path = <<UnbalancedElectrical-PerLengthLineParameter,PerLengthLineParameter>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PerLengthImpedance:
Common type for per-length electrical impedances.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PerLengthImpedance:

[[UnbalancedElectrical-PerLengthLineParameter]]
==== PerLengthLineParameter

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PerLengthLineParameter:
Common type for per-length electrical line parameters.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PerLengthLineParameter:

[[UnbalancedElectrical-PowerElectronicsUnit]]
==== PowerElectronicsUnit

Inheritance path = <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PowerElectronicsUnit:
A generating unit or battery or aggregation that connects to the AC network using power electronics rather than rotating machines.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|
Maximum active power limit. This is the maximum (nameplate) limit for the unit.

|minP
|1..1
|<<UnbalancedElectrical-ActivePower,ActivePower>>
|
Minimum active power limit. This is the minimum (nameplate) limit for the unit.

|PowerElectronicsConnection
|0..1
|<<UnbalancedElectrical-PowerElectronicsConnection,PowerElectronicsConnection>>
|
A power electronics unit has a connection to the AC network.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerElectronicsUnit:

[[UnbalancedElectrical-PowerSystemResource]]
==== PowerSystemResource

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:PowerSystemResource:
A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!PowerSystemResource:

[[UnbalancedElectrical-ProtectedSwitch]]
==== ProtectedSwitch

Inheritance path = <<UnbalancedElectrical-Switch,Switch>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ProtectedSwitch:
A ProtectedSwitch is a switching device that can be operated by ProtectionEquipment.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|
The maximum fault current a breaking device can break safely under prescribed conditions of use.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|see <<UnbalancedElectrical-Switch,Switch>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ProtectedSwitch:

[[UnbalancedElectrical-RegulatingCondEq]]
==== RegulatingCondEq

Inheritance path = <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:RegulatingCondEq:
A type of conducting equipment that can regulate a quantity (i.e. voltage or flow) at a specific point in the network.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|
The regulating control scheme in which this equipment participates.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!RegulatingCondEq:

[[UnbalancedElectrical-RegulatingControl]]
==== RegulatingControl

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:RegulatingControl:
Specifies a set of equipment that works together to control a power system quantity such as voltage or flow.

Remote bus voltage control is possible by specifying the controlled terminal located at some place remote from the controlling equipment.

The specified terminal shall be associated with the connectivity node of the controlled point. The most specific subtype of RegulatingControl shall be used in case such equipment participate in the control, e.g. TapChangerControl for tap changers.

For flow control, load sign convention is used, i.e. positive sign means flow out from a TopologicalNode (bus) into the conducting equipment.

The attribute minAllowedTargetValue and maxAllowedTargetValue are required in the following cases:

- For a power generating module operated in power factor control mode to specify maximum and minimum power factor values;

- Whenever it is necessary to have an off center target voltage for the tap changer regulator. For instance, due to long cables to off shore wind farms and the need to have a simpler setup at the off shore transformer platform, the voltage is controlled from the land at the connection point for the off shore wind farm. Since there usually is a voltage rise along the cable, there is typical and overvoltage of up 3 to 4 kV compared to the on shore station. Thus in normal operation the tap changer on the on shore station is operated with a target set point, which is in the lower parts of the dead band.

The attributes minAllowedTargetValue and maxAllowedTargetValue are not related to the attribute targetDeadband and thus they are not treated as an alternative of the targetDeadband. They are needed due to limitations in the local substation controller. The attribute targetDeadband is used to prevent the power flow from moving the tap position in circles (hunting) that is to be used regardless of the attributes minAllowedTargetValue and maxAllowedTargetValue.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|discrete
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
If true, indicates that regulation is performed in the simulation in a discrete mode. If false, indicates that non-discrete regulation is used in the simulation. This applies to equipment with discrete controls, e.g. tap changers and shunt compensators.

|enabled
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
The flag tells if regulation is enabled.

|mode (enumeration)
|0..1
|<<UnbalancedElectrical-RegulatingControlModeKind,RegulatingControlModeKind>>
|
The regulating control mode presently available. This specification allows for determining the kind of regulation without need for obtaining the units from a schedule.

|monitoredPhase (enumeration)
|0..1
|<<UnbalancedElectrical-PhaseCode,PhaseCode>>
|
Phase voltage controlling this regulator, measured at regulator location.

|targetDeadband
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
This is the deadband set on the controller. It is used with discrete control to avoid excessive tap changes in tap changers and state changes in shunt compensator banks while regulating. The units in which deadband is expressed are based on RegulatingControl.mode. The attribute shall be a positive value or zero. If RegulatingControl.discrete is set to "false", the RegulatingControl.targetDeadband is to be ignored in simulations. If TapChanger.ctRatio or TapChanger.ptRatio are populated, deadband shall be expressed in secondary units.

Note that for instance, if the targetValue is 100 kV and the targetDeadband is 2 kV the range is from 99 to 101 kV.

|targetValue
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
The target value set on the controller. It is the starting value for a steady state solution. This value can be used for the target value without the use of schedules. The value has the units appropriate to the mode attribute.

If used for a TapChangerControl and if TapChanger.ctRatio or TapChanger.ptRatio are populated, the target value shall be expressed in secondary units. As an example, with PT ratio of 60 on a 12.47 KV distribution system, a phase to ground PT has a ratio of 7200 volts primary to 120 volts secondary. If the required primary target is 7128 volts for a single phase tap changer then the value of targetValue would equal 118.8 volts secondary (7128/60).

|Terminal
|1..1
|<<UnbalancedElectrical-Terminal,Terminal>>
|
The terminal associated with this regulating control. The terminal is associated instead of a node, since the terminal could connect into either a topological node or a connectivity node. Sometimes it is useful to model regulation at a terminal of a bus bar object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!RegulatingControl:

[[UnbalancedElectrical-RotatingMachine]]
==== RotatingMachine

Inheritance path = <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:RotatingMachine:
A rotating machine which may be used as a generator or motor.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<UnbalancedElectrical-ApparentPower,ApparentPower>>
|
Nameplate apparent power rating for the unit.

The attribute shall have a positive value.

|ratedU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Rated voltage (nameplate data, Ur in IEC 60909-0). It is primarily used for short circuit data exchange according to IEC 60909.

The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!RotatingMachine:

[[UnbalancedElectrical-ShuntCompensator]]
==== ShuntCompensator

Inheritance path = <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>> => <<UnbalancedElectrical-EnergyConnection,EnergyConnection>> => <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ShuntCompensator:
A shunt capacitor or reactor or switchable bank of shunt capacitors or reactors. A section of a shunt compensator is an individual capacitor or reactor. A negative value for bPerSection indicates that the compensator is a reactor. ShuntCompensator is a single terminal device. Ground is implied.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aVRDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|
An automatic voltage regulation delay (AVRDelay) which is the time delay from a change in voltage to when the capacitor is allowed to change state. This filters out temporary changes in voltage.

|maximumSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The maximum number of sections that may be switched in.

|nomU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
The voltage at which the nominal reactive power may be calculated. This should normally be within 10% of the voltage at which the capacitor is connected to the network.

|normalSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The normal number of sections switched in. The value shall be between zero and ShuntCompensator.maximumSections.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<UnbalancedElectrical-RegulatingControl,RegulatingControl>>
|see <<UnbalancedElectrical-RegulatingCondEq,RegulatingCondEq>>
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ShuntCompensator:

[[UnbalancedElectrical-ShuntCompensatorPhase]]
==== ShuntCompensatorPhase

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:ShuntCompensatorPhase:
Single phase of a multi-phase shunt compensator when its attributes might be different per phase.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maximumSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The maximum number of sections that may be switched in for this phase.

|normalSections
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
For the capacitor phase, the normal number of sections switched in. The value shall be between zero and ShuntCompensatorPhase.maximumSections.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!ShuntCompensatorPhase:

[[UnbalancedElectrical-Switch]]
==== Switch

Inheritance path = <<UnbalancedElectrical-ConductingEquipment,ConductingEquipment>> => <<UnbalancedElectrical-Equipment,Equipment>> => <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:Switch:
A generic device designed to close, or open, or both, one or more electric circuits. All switches are two terminal devices including grounding switches. The ACDCTerminal.connected at the two sides of the switch shall not be considered for assessing switch connectivity, i.e. only Switch.open, .normalOpen and .locked are relevant.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedCurrent
|1..1
|<<UnbalancedElectrical-CurrentFlow,CurrentFlow>>
|
The maximum continuous current carrying capacity in amps governed by the device material and construction.

The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!Switch:

[[UnbalancedElectrical-TapChanger]]
==== TapChanger

Inheritance path = <<UnbalancedElectrical-PowerSystemResource,PowerSystemResource>> => <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:TapChanger:
Mechanism for changing transformer winding tap positions.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|controlEnabled
|0..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
Specifies the regulation status of the equipment. True is regulating, false is not regulating.

|[extension]#ctRating (gmdm)#
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
|ctRatio
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Built-in current transformer ratio. If a value is specified, then RegulatingControl.targetValue (and RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue and RegulatingControl.minAllowedTargetValue) are expressed in secondary units.

|highStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
Highest possible tap step position, advance from neutral.

The attribute shall be greater than lowStep.

|initialDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|
For an LTC, the delay for initial tap changer operation (first step change).

|lowStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
Lowest possible tap step position, retard from neutral.

|ltcFlag
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
Specifies whether or not a TapChanger has load tap changing capabilities.

|neutralStep
|1..1
|<<UnbalancedElectrical-Integer,Integer>>
|
The neutral tap step position for this winding.

The attribute shall be equal to or greater than lowStep and equal or less than highStep.

It is the step position where the voltage is neutralU when the other terminals of the transformer are at the ratedU. If there are other tap changers on the transformer those taps are kept constant at their neutralStep.

|neutralU
|1..1
|<<UnbalancedElectrical-Voltage,Voltage>>
|
Voltage at which the winding operates at the neutral tap setting. It is the voltage at the terminal of the PowerTransformerEnd associated with the tap changer when all tap changers on the transformer are at their neutralStep position. Normally neutralU of the tap changer is the same as ratedU of the PowerTransformerEnd, but it can differ in special cases such as when the tapping mechanism is separate from the winding more common on lower voltage transformers.

This attribute is not relevant for PhaseTapChangerAsymmetrical, PhaseTapChangerSymmetrical and PhaseTapChangerLinear.

|ptRatio
|0..1
|<<UnbalancedElectrical-Float,Float>>
|
Built-in potential (voltage) transformer ratio. If a value is specified, then RegulatingControl.targetValue (and RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue, RegulatingControl.minAllowedTargetValue as well as TapChangerControl.maxLimitVoltage and TapChangerControl.minLimitVoltage) are expressed in secondary units.

|subsequentDelay
|0..1
|<<UnbalancedElectrical-Seconds,Seconds>>
|
For an LTC, the delay for subsequent tap changer operation (second and later step changes).

|TapChangerControl
|0..1
|<<UnbalancedElectrical-TapChangerControl,TapChangerControl>>
|
The regulating control scheme in which this tap changer participates.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TapChanger:

[[UnbalancedElectrical-TransformerEnd]]
==== TransformerEnd

Inheritance path = <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>> => <<UnbalancedElectrical-Identity,Identity>>

:TransformerEnd:
A conducting connection point of a power transformer. It corresponds to a physical transformer winding terminal. In earlier CIM versions, the TransformerWinding class served a similar purpose, but this class is more flexible because it associates to terminal but is not a specialization of ConductingEquipment.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|grounded
|1..1
|<<UnbalancedElectrical-Boolean,Boolean>>
|
Used only for Yn and Zn connections indicated by PowerTransformerEnd.connectionKind. If true, the neutral is grounded and attributes TransformerEnd.rground and TransformerEnd.xground are required. If false, the attributes TransformerEnd.rground and TransformerEnd.xground are not considered.

|rground
|0..1
|<<UnbalancedElectrical-Resistance,Resistance>>
|
Resistance part of neutral impedance. Zero indicates solidly grounded or grounded through a reactor.

|xground
|0..1
|<<UnbalancedElectrical-Reactance,Reactance>>
|
Reactance part of neutral impedance. Zero indicates solidly grounded or grounded through a reactor.

|CoreAdmittance
|0..1
|<<UnbalancedElectrical-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|
Core admittance of this transformer end, representing magnetising current and core losses. The full values of the transformer should be supplied for one transformer end only.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<UnbalancedElectrical-String,String>>
|see <<UnbalancedElectrical-Identity,Identity>>
|===
:!TransformerEnd:


=== Enumerations

[[UnbalancedElectrical-ConverterControlModeKind]]
==== ConverterControlModeKind


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|constantPowerFactor
|

|constantReactivePower
|

|dynamic
|
|===
[[UnbalancedElectrical-FuelType]]
==== FuelType


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|FuelType.brownCoalLignite
|

|FuelType.coal
|

|FuelType.coalDerivedGas
|

|FuelType.diesel
|

|FuelType.gas
|

|FuelType.hardCoal
|

|FuelType.lignite
|

|FuelType.oil
|

|FuelType.oilShale
|

|FuelType.other
|

|FuelType.peat
|
|===
[[UnbalancedElectrical-PhaseCode]]
==== PhaseCode

Enumeration of phase identifiers used to designate the combination of phase and/or neutral conductors at a terminal, measurement or equipment modelled as a single-line balanced equivalent.

This is an unordered enumeration of phase identifiers. Allows designation of phases for both transmission and distribution equipment, circuits and loads. The enumeration, by itself, does not describe how the phases are connected together or connected to ground. Ground is not explicitly denoted as a phase.

Residential and small commercial loads are often served from single-phase, or split-phase, secondary circuits. For the example of s12N, phases 1 and 2 refer to hot wires that are 180 degrees out of phase, while N refers to the neutral wire. Through single-phase transformer connections, these secondary circuits may be served from one or two of the primary phases A, B, and C. For three-phase loads, use the A, B, C phase codes instead of s12N.

The integer values are from IEC 61968-9 to support revenue metering applications.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|PhaseCode.A
|

|PhaseCode.AB
|

|PhaseCode.ABC
|

|PhaseCode.ABCN
|

|PhaseCode.ABN
|

|PhaseCode.AC
|

|PhaseCode.ACN
|

|PhaseCode.AN
|

|PhaseCode.B
|

|PhaseCode.BC
|

|PhaseCode.BCN
|

|PhaseCode.BN
|

|PhaseCode.C
|

|PhaseCode.CN
|

|PhaseCode.N
|

|PhaseCode.X
|

|PhaseCode.XN
|

|PhaseCode.XY
|

|PhaseCode.XYN
|

|PhaseCode.none
|

|PhaseCode.s1
|

|PhaseCode.s12
|

|PhaseCode.s12N
|

|PhaseCode.s1N
|

|PhaseCode.s2
|

|PhaseCode.s2N
|
|===
[[UnbalancedElectrical-RegulatingControlModeKind]]
==== RegulatingControlModeKind

The kind of regulation model. For example regulating voltage, reactive power, active power, etc.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|RegulatingControlModeKind.activePower
|

|RegulatingControlModeKind.admittance
|

|RegulatingControlModeKind.currentFlow
|

|RegulatingControlModeKind.powerFactor
|

|RegulatingControlModeKind.reactivePower
|

|RegulatingControlModeKind.temperature
|

|RegulatingControlModeKind.timeScheduled
|

|RegulatingControlModeKind.voltage
|
|===
[[UnbalancedElectrical-WindGenUnitKind]]
==== WindGenUnitKind

Kind of wind generating unit.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|offshore
|
The wind generating unit is located offshore.


|onshore
|
The wind generating unit is located onshore.

|===

=== Datatypes

[[UnbalancedElectrical-ActivePower]]
==== ActivePower

Product of RMS value of the voltage and the RMS value of the in-phase component of the current.


XSD type: float

[[UnbalancedElectrical-ApparentPower]]
==== ApparentPower

Product of the RMS value of the voltage and the RMS value of the current.


XSD type: float

[[UnbalancedElectrical-Conductance]]
==== Conductance

Factor by which voltage must be multiplied to give corresponding power lost from a circuit. Real part of admittance.


XSD type: float

[[UnbalancedElectrical-CurrentFlow]]
==== CurrentFlow

Electrical current with sign convention: positive flow is out of the conducting equipment into the connectivity node. Can be both AC and DC.


XSD type: float

[[UnbalancedElectrical-Length]]
==== Length

Unit of length. It shall be a positive value or zero.


XSD type: float

[[UnbalancedElectrical-PerCent]]
==== PerCent

Percentage on a defined base. For example, specify as 100 to indicate at the defined base.


XSD type: float

[[UnbalancedElectrical-Reactance]]
==== Reactance

Reactance (imaginary part of impedance), at rated frequency.


XSD type: float

[[UnbalancedElectrical-ReactancePerLength]]
==== ReactancePerLength

Reactance (imaginary part of impedance) per unit of length, at rated frequency.


XSD type: float

[[UnbalancedElectrical-ReactivePower]]
==== ReactivePower

Product of RMS value of the voltage and the RMS value of the quadrature component of the current.


XSD type: float

[[UnbalancedElectrical-RealEnergy]]
==== RealEnergy

Real electrical energy.


XSD type: float

[[UnbalancedElectrical-Resistance]]
==== Resistance

Resistance (real part of impedance).


XSD type: float

[[UnbalancedElectrical-ResistancePerLength]]
==== ResistancePerLength

Resistance (real part of impedance) per unit of length.


XSD type: float

[[UnbalancedElectrical-Seconds]]
==== Seconds

Time, in seconds.


XSD type: float

[[UnbalancedElectrical-Susceptance]]
==== Susceptance

Imaginary part of admittance.


XSD type: float

[[UnbalancedElectrical-SusceptancePerLength]]
==== SusceptancePerLength

Imaginary part of admittance per unit of length.


XSD type: float

[[UnbalancedElectrical-Voltage]]
==== Voltage

Electrical voltage, can be both AC and DC.


XSD type: float


=== Primitive Types

[[UnbalancedElectrical-Boolean]]
==== Boolean

A type with the value space "true" and "false".http://langdale.com.au/2005/UML#primitive

XSD type: boolean

[[UnbalancedElectrical-Float]]
==== Float

A floating point number. The range is unspecified and not limited.http://langdale.com.au/2005/UML#primitive

XSD type: float

[[UnbalancedElectrical-Integer]]
==== Integer

An integer number. The range is unspecified and not limited.http://langdale.com.au/2005/UML#primitive

XSD type: integer

[[UnbalancedElectrical-String]]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.http://langdale.com.au/2005/UML#primitive

XSD type: string


