
== UsagePoint Profile Specification

// Settings:
:doctype: inline
:reproducible:
:icons: font
:sectnums:
:sectnumlevels: 4
:xrefstyle: short

Profile namespace: http://www.ucaiug.org/gmdm/usagepoint#

.Profile Profile
plantuml::./Profiles/UsagePoint.rdfs-t2b.puml[format=svg, align=center]


=== Concrete Classes

[[UsagePoint-Terminal]]
==== (Description) Terminal

Inheritance path = <<UsagePoint-ACDCTerminal,ACDCTerminal>> => <<UsagePoint-IdentifiedObject,IdentifiedObject>> => <<UsagePoint-Identity,Identity>>

ifdef::UsagePoint-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{UsagePoint-description-profile}-Terminal,Terminal>>.
endif::UsagePoint-description-profile[]

:Terminal:
An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|name
|0..1
|<<UsagePoint-String,String>>
|see <<UsagePoint-IdentifiedObject,IdentifiedObject>>
|===
:!Terminal:

[[UsagePoint-UsagePoint]]
==== UsagePoint

Inheritance path = <<UsagePoint-IdentifiedObject,IdentifiedObject>> => <<UsagePoint-Identity,Identity>>

:UsagePoint:
Logical or physical point in the network to which readings or events may be attributed. Used at the place where a physical or virtual meter may be located; however, it is not required that a meter be present.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|phaseCode (enumeration)
|0..1
|<<UsagePoint-PhaseCode,PhaseCode>>
|
Phase code. Number of wires and specific nominal phases can be deduced from enumeration literal values. For example, ABCN is three-phase, four-wire, s12n (splitSecondary12N) is single-phase, three-wire, and s1n and s2n are single-phase, two-wire.

|[extension]#Terminal#
|0..1
|<<UsagePoint-Terminal,Terminal>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|name
|0..1
|<<UsagePoint-String,String>>
|see <<UsagePoint-IdentifiedObject,IdentifiedObject>>
|===
:!UsagePoint:


=== Abstract Classes

[[UsagePoint-ACDCTerminal]]
==== ACDCTerminal

Inheritance path = <<UsagePoint-IdentifiedObject,IdentifiedObject>> => <<UsagePoint-Identity,Identity>>

:ACDCTerminal:
An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|name
|0..1
|<<UsagePoint-String,String>>
|see <<UsagePoint-IdentifiedObject,IdentifiedObject>>
|===
:!ACDCTerminal:

[[UsagePoint-IdentifiedObject]]
==== IdentifiedObject

Inheritance path = <<UsagePoint-Identity,Identity>>

:IdentifiedObject:
This is a class that provides common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|name
|0..1
|<<UsagePoint-String,String>>
|
The name is any free human readable and possibly non unique text naming the object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!IdentifiedObject:

[[UsagePoint-Identity]]
==== Identity


:Identity:
,

:!Identity:


=== Enumerations

[[UsagePoint-PhaseCode]]
==== PhaseCode

Enumeration of phase identifiers used to designate the combination of phase and/or neutral conductors at a terminal, measurement or equipment modelled as a single-line balanced equivalent.

This is an unordered enumeration of phase identifiers. Allows designation of phases for both transmission and distribution equipment, circuits and loads. The enumeration, by itself, does not describe how the phases are connected together or connected to ground. Ground is not explicitly denoted as a phase.

Residential and small commercial loads are often served from single-phase, or split-phase, secondary circuits. For the example of s12N, phases 1 and 2 refer to hot wires that are 180 degrees out of phase, while N refers to the neutral wire. Through single-phase transformer connections, these secondary circuits may be served from one or two of the primary phases A, B, and C. For three-phase loads, use the A, B, C phase codes instead of s12N.

The integer values are from IEC 61968-9 to support revenue metering applications.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|A
|
Phase A.


|AB
|
Phases A and B.


|ABC
|
Phases A, B, and C.


|ABCN
|
Phases A, B, C, and N.


|ABN
|
Phases A, B, and neutral.


|AC
|
Phases A and C.


|ACN
|
Phases A, C and neutral.


|AN
|
Phases A and neutral.


|B
|
Phase B.


|BC
|
Phases B and C.


|BCN
|
Phases B, C, and neutral.


|BN
|
Phases B and neutral.


|C
|
Phase C.


|CN
|
Phases C and neutral.


|N
|
Neutral phase.


|X
|
Unknown non-neutral phase.


|XN
|
Unknown non-neutral phase plus neutral.


|XY
|
Two unknown non-neutral phases.


|XYN
|
Two unknown non-neutral phases plus neutral.


|none
|
No phases specified.


|s1
|
Secondary phase 1.


|s12
|
Secondary phase 1 and 2.


|s12N
|
Secondary phases 1, 2, and neutral.


|s1N
|
Secondary phase 1 and neutral.


|s2
|
Secondary phase 2.


|s2N
|
Secondary phase 2 and neutral.

|===

=== Primitive Types

[[UsagePoint-String]]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.http://langdale.com.au/2005/UML#primitive

XSD type: string


