
== UnbalancedElectrical Profile Specification

// Settings:
:doctype: inline
:reproducible:
:icons: font
:sectnums:
:sectnumlevels: 4
:xrefstyle: short

Profile namespace: http://www.ucaiug.org/gmdm/electrical/unbalanced#

.UnbalancedElectrical Profile
plantuml::./Profiles/merged_ontology.rdfs-t2b.puml[format=svg, align=center]


=== Concrete Classes

[[merged_ontology-ACLineSegment]]
==== (Description) ACLineSegment

Inheritance path = <<merged_ontology-Conductor,Conductor>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-ACLineSegment,ACLineSegment>>.
endif::merged_ontology-description-profile[]

:ACLineSegment:
A line segment is a conductor or combination of conductors, with consistent electrical characteristics along its length, building a single electrical system that carries alternating current between two points in the power system.

The BaseVoltage at the two ends of a line segment shall have the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly different BaseVoltage.nominalVoltages and variation is allowed. Larger voltage difference in general requires use of an equivalent branch.

Line segment impedances can be either directly described in electrical terms or physical line detail can be provided from which impedances can be calculated.

{lt}b{gt}Directly described impedances{lt}/b{gt}

For symmetrical, transposed three phase line segments, it is sufficient to use attributes of the line segment, which describe impedances and admittances for the entire length of the line segment. Additionally, line segment impedances can be computed by using line segment length and associated per length impedances.

Unbalanced modeling of impedances is supported by the per length phase impedance matrix (PerLengthPhaseImpedance) in conjunction with phase-to-sequence number mapping supplied by either ACLineSegmentPhase or WirePosition. The sequence numbers are referenced by the row and column attributes of the per length phase impedance matrix. This method enables single-phase and two-phase line segments, and transpositions of phases, to be described using the same per length phase impedance matrix. The length of the line segment is used in the computation of total impedance values for the line segment.

{lt}b{gt}Line detail characteristics{lt}/b{gt}

There are three approaches to providing line detail and all use WireAssembly to supply line positions:

{lt}ul{gt}

{lt}li{gt}Option 1 - WireAssembly supplies only line positions. ACLineSegmentPhase points to wire type and intraphase spacing and supplies the phase-to-sequence number mapping.{lt}/li{gt}

{lt}li{gt}Option 2 - WireAssembly supplies line position and, for each position, also supplies wire type and intraphase spacing. ACLineSegmentPhase supplies the phase-to-sequence number mapping.{lt}/li{gt}

{lt}li{gt}Option 3 - WireAssembly supplies line position and, for each position, also supplies wire type and intraphase spacing and phase. WireAssembly therefore supplies the phase-to-sequence number mapping and ACLineSegmentPhase is not needed.{lt}/li{gt}

{lt}/ul{gt}


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|PerLengthImpedance
|1..1
|<<merged_ontology-PerLengthImpedance,PerLengthImpedance>>
|
Per-length impedance of this line segment.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|length
|1..1
|<<merged_ontology-Length,Length>>
|see <<merged_ontology-Conductor,Conductor>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ACLineSegment:

[[merged_ontology-ACLineSegmentPhase]]
==== (Description) ACLineSegmentPhase

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-ACLineSegmentPhase,ACLineSegmentPhase>>.
endif::merged_ontology-description-profile[]

:ACLineSegmentPhase:
A line segment phase represents one phase (or optionally the neutral) of an alternating current line segment.

Under most circumstances there is not a line segment phase for the neutral. However, if a wire assembly is being used and it does not specify phase, a line segment phase must exist for each position in the assembly (including the neutral).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|phase (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase identifies the phase or neutral connection of the conductor at both ends.

|sequenceNumber
|1..1
|<<merged_ontology-Integer,Integer>>
|
Sequence number provides the numbering for this line segment phase. When impedance is directly described, sequence number binds the phase to the column and row for entries in the per length phase impedance matrix (PhaseImpedanceData of PerLengthPhaseImpedance). When used in conjunction with a wire assembly description, sequence number associates the line segment phase to a position.

For a line segment not a part of a parallel line segment group, sequence number starts at one and increments by one through each line segment phase associated with the line segment. If there is a line segment phase for neutral, it is numbered last.

|ACLineSegment
|0..1
|<<merged_ontology-ACLineSegment,ACLineSegment>>
|
The line segment to which the phase belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ACLineSegmentPhase:

[[merged_ontology-AsynchronousMachine]]
==== (Description) AsynchronousMachine

Inheritance path = <<merged_ontology-RotatingMachine,RotatingMachine>> => <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-AsynchronousMachine,AsynchronousMachine>>.
endif::merged_ontology-description-profile[]

:AsynchronousMachine:
A rotating machine whose shaft rotates asynchronously with the electrical field. Also known as an induction machine with no external connection to the rotor windings, e.g. squirrel-cage induction machine.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|see <<merged_ontology-RotatingMachine,RotatingMachine>>
|ratedU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|see <<merged_ontology-RotatingMachine,RotatingMachine>>
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!AsynchronousMachine:

[[merged_ontology-BaseVoltage]]
==== BaseVoltage


:BaseVoltage:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|nominalVoltage
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
The power system resource's base voltage, expressed on a phase-to-phase (line-to-line) basis. Shall be a positive value and not zero.

|===
:!BaseVoltage:

[[merged_ontology-BatteryUnit]]
==== BatteryUnit

Inheritance path = <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:BatteryUnit:
An electrochemical energy storage device.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedE
|0..1
|<<merged_ontology-RealEnergy,RealEnergy>>
|
Full energy storage capacity of the battery. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!BatteryUnit:

[[merged_ontology-Breaker]]
==== (Description) Breaker

Inheritance path = <<merged_ontology-ProtectedSwitch,ProtectedSwitch>> => <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Breaker,Breaker>>.
endif::merged_ontology-description-profile[]

:Breaker:
A mechanical switching device capable of making, carrying, and breaking currents under normal circuit conditions and also making, carrying for a specified time, and breaking currents under specified abnormal circuit conditions e.g. those of short circuit.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-ProtectedSwitch,ProtectedSwitch>>
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Breaker:

[[merged_ontology-BusbarSection]]
==== (Description) BusbarSection

Inheritance path = <<merged_ontology-Connector,Connector>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-BusbarSection,BusbarSection>>.
endif::merged_ontology-description-profile[]

:BusbarSection:
A conductor, or group of conductors, with negligible impedance, that serve to connect other conducting equipment within a single substation. The BusbarSection class is intended to represent physical parts of bus bars no matter how that bus bar is constructed.

Voltage measurements are typically obtained from voltage transformers that are connected to busbar sections. A bus bar section may have many physical terminals but for analysis is modelled with exactly one logical terminal.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!BusbarSection:

[[merged_ontology-ConnectivityNode]]
==== (Description) ConnectivityNode

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-ConnectivityNode,ConnectivityNode>>.
endif::merged_ontology-description-profile[]

:ConnectivityNode:
Connectivity nodes are points where terminals of AC conducting equipment are connected together with zero impedance.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ConnectivityNode:

[[merged_ontology-CoordinateSystem]]
==== CoordinateSystem


:CoordinateSystem:
:!CoordinateSystem:

[[merged_ontology-Diagram]]
==== Diagram


:Diagram:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|orientation (enumeration)
|0..1
|<<merged_ontology-OrientationKind,OrientationKind>>
|
Coordinate system orientation of the diagram. A positive orientation gives standard "right-hand" orientation, with negative orientation indicating a "left-hand" orientation. For 2D diagrams, a positive orientation will result in X values increasing from left to right and Y values increasing from bottom to top. A negative orientation gives the "left-hand" orientation (favoured by computer graphics displays) with X values increasing from left to right and Y values increasing from top to bottom.

|x1InitialView
|0..1
|<<merged_ontology-Float,Float>>
|
X coordinate of the first corner of the initial view.

|x2InitialView
|0..1
|<<merged_ontology-Float,Float>>
|
X coordinate of the second corner of the initial view.

|y1InitialView
|0..1
|<<merged_ontology-Float,Float>>
|
Y coordinate of the first corner of the initial view.

|y2InitialView
|0..1
|<<merged_ontology-Float,Float>>
|
Y coordinate of the second corner of the initial view.

|DiagramStyle
|0..1
|<<merged_ontology-DiagramStyle,DiagramStyle>>
|
A Diagram may have a DiagramStyle.

|===
:!Diagram:

[[merged_ontology-DiagramObject]]
==== DiagramObject


:DiagramObject:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|drawingOrder
|0..1
|<<merged_ontology-Integer,Integer>>
|
The drawing order of this element. The higher the number, the later the element is drawn in sequence. This is used to ensure that elements that overlap are rendered in the correct order.

|isPolygon
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Defines whether or not the diagram objects points define the boundaries of a polygon or the routing of a polyline. If this value is true then a receiving application should consider the first and last points to be connected.

|offsetX
|0..1
|<<merged_ontology-Float,Float>>
|
The offset in the X direction. This is used for defining the offset from centre for rendering an icon (the default is that a single point specifies the centre of the icon).

The offset is in per-unit with 0 indicating there is no offset from the horizontal centre of the icon. -0.5 indicates it is offset by 50% to the left and 0.5 indicates an offset of 50% to the right.

|offsetY
|0..1
|<<merged_ontology-Float,Float>>
|
The offset in the Y direction. This is used for defining the offset from centre for rendering an icon (the default is that a single point specifies the centre of the icon).

The offset is in per-unit with 0 indicating there is no offset from the vertical centre of the icon. The offset direction is dependent on the orientation of the diagram, with -0.5 and 0.5 indicating an offset of +/- 50% on the vertical axis.

|rotation
|0..1
|<<merged_ontology-AngleDegrees,AngleDegrees>>
|
Sets the angle of rotation of the diagram object. Zero degrees is pointing to the top of the diagram. Rotation is clockwise. DiagramObject.rotation=0 has the following meaning: The connection point of an element which has one terminal is pointing to the top side of the diagram. The connection point "From side" of an element which has more than one terminal is pointing to the top side of the diagram.

DiagramObject.rotation=90 has the following meaning: The connection point of an element which has one terminal is pointing to the right hand side of the diagram. The connection point "From side" of an element which has more than one terminal is pointing to the right hand side of the diagram.

|Diagram
|1..1
|<<merged_ontology-Diagram,Diagram>>
|
A diagram object is part of a diagram.

|DiagramObjectStyle
|1..1
|<<merged_ontology-DiagramObjectStyle,DiagramObjectStyle>>
|
A diagram object has a style associated that provides a reference for the style used in the originating system.

|===
:!DiagramObject:

[[merged_ontology-DiagramObjectGluePoint]]
==== DiagramObjectGluePoint


:DiagramObjectGluePoint:
This is used for grouping diagram object points from different diagram objects that are considered to be glued together in a diagram even if they are not at the exact same coordinates.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|DiagramObjectPoints
|1..*
|<<merged_ontology-DiagramObjectPoint,DiagramObjectPoint>>
|
A diagram object glue point is associated with 2 or more object points that are considered to be 'glued' together.

|===
:!DiagramObjectGluePoint:

[[merged_ontology-DiagramObjectPoint]]
==== DiagramObjectPoint


:DiagramObjectPoint:
A point in a given space defined by 3 coordinates and associated to a diagram object. The coordinates may be positive or negative as the origin does not have to be in the corner of a diagram.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|sequenceNumber
|0..1
|<<merged_ontology-Integer,Integer>>
|
The sequence position of the point, used for defining the order of points for diagram objects acting as a polyline or polygon with more than one point. The attribute shall be a positive value.

|xPosition
|1..1
|<<merged_ontology-Float,Float>>
|
The X coordinate of this point.

|yPosition
|1..1
|<<merged_ontology-Float,Float>>
|
The Y coordinate of this point.

|zPosition
|0..1
|<<merged_ontology-Float,Float>>
|
The Z coordinate of this point.

|DiagramObject
|1..1
|<<merged_ontology-DiagramObject,DiagramObject>>
|
The diagram object with which the points are associated.

|===
:!DiagramObjectPoint:

[[merged_ontology-DiagramObjectStyle]]
==== DiagramObjectStyle


:DiagramObjectStyle:
A reference to a style used by the originating system for a diagram object. A diagram object style describes information such as line thickness, shape such as circle or rectangle etc, and colour.

:!DiagramObjectStyle:

[[merged_ontology-DiagramStyle]]
==== DiagramStyle


:DiagramStyle:
:!DiagramStyle:

[[merged_ontology-Disconnector]]
==== (Description) Disconnector

Inheritance path = <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Disconnector,Disconnector>>.
endif::merged_ontology-description-profile[]

:Disconnector:
A mechanical switching device which provides, in the open position, an isolating distance in accordance with specified requirements.

A disconnector is capable of opening and closing a circuit when either negligible current is broken or made, or when no significant change in the voltage across the terminals of each of the poles of the disconnector occurs. It is also capable of carrying currents under normal circuit conditions and carrying for a specified time currents under abnormal conditions such as those of short circuit.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Disconnector:

[[merged_ontology-EnergyConsumer]]
==== (Description) EnergyConsumer

Inheritance path = <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-EnergyConsumer,EnergyConsumer>>.
endif::merged_ontology-description-profile[]

:EnergyConsumer:
Generic user of energy - a point of consumption on the power system model.

EnergyConsumer.pfixed, .qfixed, .pfixedPct and .qfixedPct have meaning only if there is no LoadResponseCharacteristic associated with EnergyConsumer or if LoadResponseCharacteristic.exponentModel is set to False.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|customerCount
|0..1
|<<merged_ontology-Integer,Integer>>
|
Number of individual customers represented by this demand.

|grounded
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Required for Yn and I connections (as represented by EnergyConsumer.phaseConnection). True if the neutral is solidly grounded.

|phaseConnection (enumeration)
|1..1
|<<merged_ontology-PhaseShuntConnectionKind,PhaseShuntConnectionKind>>
|
The type of phase connection, such as wye or delta.

|LoadResponse
|0..1
|<<merged_ontology-LoadResponseCharacteristic,LoadResponseCharacteristic>>
|
The load response characteristic of this load. If missing, this load is assumed to be constant power.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!EnergyConsumer:

[[merged_ontology-EnergyConsumerPhase]]
==== EnergyConsumerPhase


:EnergyConsumerPhase:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|phase (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase of this energy consumer component. If the energy consumer is wye connected, the connection is from the indicated phase to the central ground or neutral point. If the energy consumer is delta connected, the phase indicates an energy consumer connected from the indicated phase to the next logical non-neutral phase.

|EnergyConsumer
|1..1
|<<merged_ontology-EnergyConsumer,EnergyConsumer>>
|
The energy consumer to which this phase belongs.

|===
:!EnergyConsumerPhase:

[[merged_ontology-EnergySource]]
==== (Description) EnergySource

Inheritance path = <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-EnergySource,EnergySource>>.
endif::merged_ontology-description-profile[]

:EnergySource:
A generic equivalent for an energy supplier on a transmission or distribution voltage level.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|nominalVoltage
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Phase-to-phase nominal voltage.

|r
|1..1
|<<merged_ontology-Resistance,Resistance>>
|
Positive sequence Thevenin resistance.

|x
|1..1
|<<merged_ontology-Reactance,Reactance>>
|
Positive sequence Thevenin reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!EnergySource:

[[merged_ontology-Feeder]]
==== Feeder

Inheritance path = <<merged_ontology-EquipmentContainer,EquipmentContainer>>

:Feeder:
A collection of equipment for organizational purposes, used for grouping distribution resources.

The organization a feeder does not necessarily reflect connectivity or current operation state.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|NormalEnergizingSubstation (OfAggregate)
|1..1
|<<merged_ontology-Substation,Substation>>
|
The substation that nominally energizes the feeder. Also used for naming purposes.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!Feeder:

[[merged_ontology-FossilFuel]]
==== FossilFuel

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:FossilFuel:
The fossil fuel consumed by the non-nuclear thermal generating unit. For example, coal, oil, gas, etc. These are the specific fuels that the generating unit can consume.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|fossilFuelType (enumeration)
|1..1
|<<merged_ontology-FuelType,FuelType>>
|
The type of fossil fuel, such as coal, oil, or gas.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!FossilFuel:

[[merged_ontology-Fuse]]
==== (Description) Fuse

Inheritance path = <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Fuse,Fuse>>.
endif::merged_ontology-description-profile[]

:Fuse:
An overcurrent protective device with a circuit opening fusible part that is heated and severed by the passage of overcurrent through it. A fuse is considered a switching device because it breaks current.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Fuse:

[[merged_ontology-IndividualPnode]]
==== IndividualPnode

Inheritance path = <<merged_ontology-Pnode,Pnode>>

:IndividualPnode:
Individual pricing node based on Pnode.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ConnectivityNode
|1..1
|<<merged_ontology-ConnectivityNode,ConnectivityNode>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!IndividualPnode:

[[merged_ontology-Line]]
==== Line

Inheritance path = <<merged_ontology-EquipmentContainer,EquipmentContainer>>

:Line:
Contains equipment beyond a substation belonging to a power transmission line.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!Line:

[[merged_ontology-LinearShuntCompensator]]
==== (Description) LinearShuntCompensator

Inheritance path = <<merged_ontology-ShuntCompensator,ShuntCompensator>> => <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-LinearShuntCompensator,LinearShuntCompensator>>.
endif::merged_ontology-description-profile[]

:LinearShuntCompensator:
A linear shunt compensator has banks or sections with equal admittance values.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|bPerSection
|1..1
|<<merged_ontology-Susceptance,Susceptance>>
|
Positive sequence shunt (charging) susceptance per section.

|gPerSection
|1..1
|<<merged_ontology-Conductance,Conductance>>
|
Positive sequence shunt (charging) conductance per section.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aVRDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|grounded
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|maximumSections
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|nomU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|normalSections
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|phaseConnection (enumeration)
|0..1
|<<merged_ontology-PhaseShuntConnectionKind,PhaseShuntConnectionKind>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|ShuntCompensatorPhase
|0..*
|<<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|see <<merged_ontology-ShuntCompensator,ShuntCompensator>>
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!LinearShuntCompensator:

[[merged_ontology-LinearShuntCompensatorPhase]]
==== (Description) LinearShuntCompensatorPhase

Inheritance path = <<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-LinearShuntCompensatorPhase,LinearShuntCompensatorPhase>>.
endif::merged_ontology-description-profile[]

:LinearShuntCompensatorPhase:
A per phase linear shunt compensator has banks or sections with equal admittance values.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|bPerSection
|1..1
|<<merged_ontology-Susceptance,Susceptance>>
|
Susceptance per section of the phase if shunt compensator is wye connected. Susceptance per section phase to phase if shunt compensator is delta connected.

|gPerSection
|1..1
|<<merged_ontology-Conductance,Conductance>>
|
Conductance per section for this phase if shunt compensator is wye connected. Conductance per section phase to phase if shunt compensator is delta connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maximumSections
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|normalSections
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|phase (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|see <<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|ShuntCompensator
|1..1
|<<merged_ontology-ShuntCompensator,ShuntCompensator>>
|see <<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!LinearShuntCompensatorPhase:

[[merged_ontology-LoadBreakSwitch]]
==== (Description) LoadBreakSwitch

Inheritance path = <<merged_ontology-ProtectedSwitch,ProtectedSwitch>> => <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-LoadBreakSwitch,LoadBreakSwitch>>.
endif::merged_ontology-description-profile[]

:LoadBreakSwitch:
A mechanical switching device capable of making, carrying, and breaking currents under normal operating conditions.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-ProtectedSwitch,ProtectedSwitch>>
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!LoadBreakSwitch:

[[merged_ontology-LoadResponseCharacteristic]]
==== LoadResponseCharacteristic

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:LoadResponseCharacteristic:
Models the characteristic response of the load demand due to changes in system conditions such as voltage and frequency. It is not related to demand response.

If LoadResponseCharacteristic.exponentModel is True, the exponential voltage or frequency dependent models are specified and used as to calculate active and reactive power components of the load model.

The equations to calculate active and reactive power components of the load model are internal to the power flow calculation, hence they use different quantities depending on the use case of the data exchange.

The equations for exponential voltage dependent load model injected power are:

pInjection= Pnominal{asterisk} (Voltage/cim:BaseVoltage.nominalVoltage) {asterisk}{asterisk} cim:LoadResponseCharacteristic.pVoltageExponent

qInjection= Qnominal{asterisk} (Voltage/cim:BaseVoltage.nominalVoltage) {asterisk}{asterisk} cim:LoadResponseCharacteristic.qVoltageExponent

pInjection = Pnominal{asterisk} (Frequency/(Nominal frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pFrequencyExponent

qInjection = Qnominal{asterisk} (Frequency/(Nominal frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qFrequencyExponent

Note that both voltage and frequency exponents could be used together so the full equation would be:

pInjection = Pnominal{asterisk} (Voltage/(cim:BaseVoltage.nominalVoltage)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pVoltageExponent {asterisk} (Frequency/(base frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.pFrequencyExponent

qInjection = Qnominal{asterisk} (Voltage/(cim:BaseVoltage.nominalVoltage)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qVoltageExponent {asterisk} (Frequency/(base frequency)){asterisk}{asterisk}cim:LoadResponseCharacteristic.qFrequencyExponent

The voltage and frequency expressed in the equation are values obtained from solved power flow. Base voltage and base frequency are those derived from the connectivity of the static network model.

Where:

1) {asterisk} means "multiply" and {asterisk}{asterisk} is "raised to the power of";

2) Pnominal and Qnominal represent the active power and reactive power at nominal voltage as any load described by the voltage exponential model shall be given at nominal voltage. This means that EnergyConsumer.p and EnergyConsumer.q are at nominal voltage.

3) After power flow is solved:

-pInjection and qInjection correspond to SvPowerflow.p and SvPowerflow.q respectively.

- Voltage corresponds to SvVoltage.v at the TopologicalNode where the load is connected.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|exponentModel
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Indicates the exponential voltage dependency model is to be used. If false, the coefficient model is to be used.

The exponential voltage dependency model consist of the attributes:

- pVoltageExponent

- qVoltageExponent

- pFrequencyExponent

- qFrequencyExponent.

The coefficient model consist of the attributes:

- pConstantImpedance

- pConstantCurrent

- pConstantPower

- qConstantImpedance

- qConstantCurrent

- qConstantPower.

The sum of pConstantImpedance, pConstantCurrent and pConstantPower shall equal 1.

The sum of qConstantImpedance, qConstantCurrent and qConstantPower shall equal 1.

|pConstantCurrent
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of active power load modelled as constant current.

|pConstantImpedance
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of active power load modelled as constant impedance.

|pConstantPower
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of active power load modelled as constant power.

|pFrequencyExponent
|0..1
|<<merged_ontology-Float,Float>>
|
Exponent of per unit frequency effecting active power.

|pVoltageExponent
|0..1
|<<merged_ontology-Float,Float>>
|
Exponent of per unit voltage effecting real power.

|qConstantCurrent
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of reactive power load modelled as constant current.

|qConstantImpedance
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of reactive power load modelled as constant impedance.

|qConstantPower
|0..1
|<<merged_ontology-Float,Float>>
|
Portion of reactive power load modelled as constant power.

|qFrequencyExponent
|0..1
|<<merged_ontology-Float,Float>>
|
Exponent of per unit frequency effecting reactive power.

|qVoltageExponent
|0..1
|<<merged_ontology-Float,Float>>
|
Exponent of per unit voltage effecting reactive power.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!LoadResponseCharacteristic:

[[merged_ontology-Location]]
==== Location


:Location:
The place, scene, or point of something where someone or something has been, is, and/or will be at a given moment in time. It can be defined with one or more position points (coordinates) in a given coordinate system.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|CoordinateSystem
|0..1
|<<merged_ontology-CoordinateSystem,CoordinateSystem>>
|
Coordinate system used to describe position points of this location.

|===
:!Location:

[[merged_ontology-NoLoadTest]]
==== NoLoadTest

Inheritance path = <<merged_ontology-TransformerTest,TransformerTest>>

:NoLoadTest:
No-load test results determine core admittance parameters. They include exciting current and core loss measurements from applying voltage to one winding. The excitation may be positive sequence or zero sequence. The test may be repeated at different voltages to measure saturation.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|energisedEndVoltage
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
Voltage applied to the winding (end) during test.

|excitingCurrent
|0..1
|<<merged_ontology-PerCent,PerCent>>
|
Exciting current measured from a positive-sequence or single-phase excitation test.

|excitingCurrentZero
|0..1
|<<merged_ontology-PerCent,PerCent>>
|
Exciting current measured from a zero-sequence open-circuit excitation test.

|loss
|0..1
|<<merged_ontology-KiloActivePower,KiloActivePower>>
|
Losses measured from a positive-sequence or single-phase excitation test.

|lossZero
|0..1
|<<merged_ontology-KiloActivePower,KiloActivePower>>
|
Losses measured from a zero-sequence excitation test.

|EnergisedEnd
|1..1
|<<merged_ontology-TransformerEndInfo,TransformerEndInfo>>
|
Transformer end that current is applied to in this no-load test.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|basePower
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|see <<merged_ontology-TransformerTest,TransformerTest>>
|temperature
|1..1
|<<merged_ontology-Temperature,Temperature>>
|see <<merged_ontology-TransformerTest,TransformerTest>>
|===
:!NoLoadTest:

[[merged_ontology-PerLengthPhaseImpedance]]
==== PerLengthPhaseImpedance

Inheritance path = <<merged_ontology-PerLengthImpedance,PerLengthImpedance>> => <<merged_ontology-PerLengthLineParameter,PerLengthLineParameter>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PerLengthPhaseImpedance:
The per length phase impedance matrix expresses impedance and admittance parameters per unit length for n-conductor unbalanced line segments. A phase impedance matrix contains both self impedances for each phase and mutual impedances between pairs of phases. The matrix is stored in symmetric lower triangular format where the diagonal entries represent self-impedances (and have the same value in row and column) and the off diagonal entries represent phase-to-phase impedances (and have different row and column values).

The matrix can be use to express impedances for both non-coupled and coupled line segments. Coupled line segments share a single per length phase impedance matrix whose entries reflect the self and mutual impedances of all the phases of all the wires.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|conductorCount
|1..1
|<<merged_ontology-Integer,Integer>>
|
Conductor count identifies the number of phase, neutral, and other wires represented in the phase impedance matrix and constrains the number of elements in the matrix. Typically, Kron reduction is used for incorporating effects of neutral impedance in the phase conductor values (so conductor count only considers phase wires), but neutrals can be included in the matrix (in which case conductor count would include the neutral wire(s)). For a phase impedance matrix associated with the lines of a coupled line segment group, the conductor count reflects the total of the conductors associated with all the coupled line segments in the group.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PerLengthPhaseImpedance:

[[merged_ontology-PhaseImpedanceData]]
==== PhaseImpedanceData

Inheritance path = <<merged_ontology-Identity,Identity>>

:PhaseImpedanceData:
Per length phase impedance matrix entry describes impedance and conductance matrix element values for a specific row and column of the matrix.

The phases to which each entry applies can be determined by means of the row and column attributes which bind to a sequence number provided in either ACLineSegmentPhase or WirePosition (which also specify phase). Due to physical symmetry that is reflected in the matrix, only the lower triangle of the matrix is populated with the row and column method. That is, the column attribute is always less than or equal to the row attribute.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|1..1
|<<merged_ontology-SusceptancePerLength,SusceptancePerLength>>
|
Susceptance matrix entry value, per length of unit.

|column
|1..1
|<<merged_ontology-Integer,Integer>>
|
The matrix entry's column number has a range of possible values from 1 to the conductor count of the matrix, but due to symmetry, only entries in the lower triangle (including diagonal) of the matrix need be defined. Column number binds to the sequence number in either ACLineSegmentPhase or WirePosition, which then identifies the phase for this entry.

|r
|1..1
|<<merged_ontology-ResistancePerLength,ResistancePerLength>>
|
Resistance matrix entry value, per length of unit.

|row
|1..1
|<<merged_ontology-Integer,Integer>>
|
The matrix entry's row number has a range of possible values from 1 to the conductor count of the matrix, but due to symmetry, only entries in the lower triangle (including diagonal) of the matrix need be defined. Row number binds to the sequence number in either ACLineSegmentPhase or WirePosition, which then identifies the phase for this entry.

|x
|1..1
|<<merged_ontology-ReactancePerLength,ReactancePerLength>>
|
Reactance matrix entry value, per length of unit.

|PhaseImpedance
|1..1
|<<merged_ontology-PerLengthPhaseImpedance,PerLengthPhaseImpedance>>
|
Conductor phase impedance to which this data belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PhaseImpedanceData:

[[merged_ontology-PhotoVoltaicUnit]]
==== PhotoVoltaicUnit

Inheritance path = <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PhotoVoltaicUnit:
A photovoltaic device or an aggregation of such devices.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PhotoVoltaicUnit:

[[merged_ontology-PositionPoint]]
==== PositionPoint


:PositionPoint:
Set of spatial coordinates that determine a point, defined in the coordinate system specified in 'Location.CoordinateSystem'. Use a single position point instance to describe a point-oriented location. Use a sequence of position points to describe a line-oriented object (physical location of non-point oriented objects like cables or lines), or area of an object (like a substation or a geographical zone - in this case, have first and last position point with the same values).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#sequenceNumber#
|1..1
|<<merged_ontology-Integer,Integer>>
|
|xPosition
|1..1
|<<merged_ontology-String,String>>
|
X axis position.

|yPosition
|1..1
|<<merged_ontology-String,String>>
|
Y axis position.

|zPosition
|0..1
|<<merged_ontology-String,String>>
|
(if applicable) Z axis position.

|[extension]#Location#
|1..1
|<<merged_ontology-Location,Location>>
|
|===
:!PositionPoint:

[[merged_ontology-PowerElectronicsConnection]]
==== (Description) PowerElectronicsConnection

Inheritance path = <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-PowerElectronicsConnection,PowerElectronicsConnection>>.
endif::merged_ontology-description-profile[]

:PowerElectronicsConnection:
A connection to the AC network for energy production or consumption that uses power electronics rather than rotating machines.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#controlMode (enumeration, gmdm)#
|0..1
|<<merged_ontology-ConverterControlModeKind,ConverterControlModeKind>>
|
Inverter control mode indicating whether reactive power output is based on constant PF or constant Q

|maxQ
|0..1
|<<merged_ontology-ReactivePower,ReactivePower>>
|
Maximum reactive power limit. This is the maximum (nameplate) limit for the unit.

|minQ
|0..1
|<<merged_ontology-ReactivePower,ReactivePower>>
|
Minimum reactive power limit for the unit. This is the minimum (nameplate) limit for the unit.

|ratedS
|0..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Nameplate apparent power rating for the unit.

The attribute shall have a positive value.

|ratedU
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
Rated voltage (nameplate data, Ur in IEC 60909-0). It is primarily used for short circuit data exchange according to IEC 60909.

The attribute shall be a positive value.

|PowerElectronicsConnectionPhase
|0..*
|<<merged_ontology-PowerElectronicsConnectionPhase,PowerElectronicsConnectionPhase>>
|
The individual phases models for the power electronics connection.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerElectronicsConnection:

[[merged_ontology-PowerElectronicsConnectionPhase]]
==== PowerElectronicsConnectionPhase


:PowerElectronicsConnectionPhase:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|phase (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase of this energy producer component. If the energy producer is wye connected, the connection is from the indicated phase to the central ground or neutral point. If the energy producer is delta connected, the phase indicates an energy producer connected from the indicated phase to the next logical non-neutral phase.

|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|
Power electronics connection of this power electronics connection phase.

|===
:!PowerElectronicsConnectionPhase:

[[merged_ontology-PowerElectronicsThermalUnit]]
==== PowerElectronicsThermalUnit

Inheritance path = <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PowerElectronicsThermalUnit:
A thermal unit that is connected via an inverter such as through a back-to-back converter


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#FossilFuels#
|0..1
|<<merged_ontology-FossilFuel,FossilFuel>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerElectronicsThermalUnit:

[[merged_ontology-PowerElectronicsWindUnit]]
==== PowerElectronicsWindUnit

Inheritance path = <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PowerElectronicsWindUnit:
A wind generating unit that connects to the AC network with power electronics rather than rotating machines or an aggregation of such units.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|minP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|see <<merged_ontology-PowerElectronicsUnit,PowerElectronicsUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerElectronicsWindUnit:

[[merged_ontology-PowerTransformer]]
==== (Description) PowerTransformer

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-PowerTransformer,PowerTransformer>>.
endif::merged_ontology-description-profile[]

:PowerTransformer:
An electrical device consisting of two or more coupled windings, with or without a magnetic core, for introducing mutual coupling between electric circuits. Transformers can be used to control voltage and phase shift (active power flow).

A power transformer may be composed of separate transformer tanks that need not be identical.

A power transformer can be modelled with or without tanks and is intended for use in both balanced and unbalanced representations. A power transformer typically has two terminals, but may have one (grounding), three or more terminals.

The inherited association ConductingEquipment.BaseVoltage should not be used. The association from TransformerEnd to BaseVoltage should be used instead.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|vectorGroup
|1..1
|<<merged_ontology-String,String>>
|
Vector group of the transformer for protective relaying, e.g., Dyn1. For unbalanced transformers, this may not be simply determined from the constituent winding connections and phase angle displacements.

The vectorGroup string consists of the following components in the order listed: high voltage winding connection, mid voltage winding connection (for three winding transformers), phase displacement clock number from 0 to 11, low voltage winding connection

phase displacement clock number from 0 to 11. The winding connections are D (delta), Y (wye), YN (wye with neutral), Z (zigzag), ZN (zigzag with neutral), A (auto transformer). Upper case means the high voltage, lower case mid or low. The high voltage winding always has clock position 0 and is not included in the vector group string. Some examples: YNy0 (two winding wye to wye with no phase displacement), YNd11 (two winding wye to delta with 330 degrees phase displacement), YNyn0d5 (three winding transformer wye with neutral high voltage, wye with neutral mid voltage and no phase displacement, delta low voltage with 150 degrees displacement).

Phase displacement is defined as the angular difference between the phasors representing the voltages between the neutral point (real or imaginary) and the corresponding terminals of two windings, a positive sequence voltage system being applied to the high-voltage terminals, following each other in alphabetical sequence if they are lettered, or in numerical sequence if they are numbered: the phasors are assumed to rotate in a counter-clockwise sense.

|PowerTransformerEnd
|1..*
|<<merged_ontology-PowerTransformerEnd,PowerTransformerEnd>>
|
The ends of this power transformer.

|TransformerTanks
|0..*
|<<merged_ontology-TransformerTank,TransformerTank>>
|
All transformers that belong to this bank.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerTransformer:

[[merged_ontology-PowerTransformerEnd]]
==== (Description) PowerTransformerEnd

Inheritance path = <<merged_ontology-TransformerEnd,TransformerEnd>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-PowerTransformerEnd,PowerTransformerEnd>>.
endif::merged_ontology-description-profile[]

:PowerTransformerEnd:
A PowerTransformerEnd is associated with each Terminal of a PowerTransformer.

The impedance values r, r0, x, and x0 of a PowerTransformerEnd represents a star equivalent as follows.

1) two PowerTransformerEnd-s shall be defined for a two Terminal PowerTransformer even if the two PowerTransformerEnd-s have the same rated voltage. The high voltage PowerTransformerEnd (TransformerEnd.endNumber=1) is the one used to exchange resistances (r, r0) and reactances (x, x0) of the PowerTransformer while the low voltage PowerTransformerEnd (TransformerEnd.endNumber=2) shall have zero impedance values.

2) for a three Terminal PowerTransformer the three PowerTransformerEnds represent a star equivalent with each leg in the star represented by r, r0, x, and x0 values.

3) For a three Terminal transformer each PowerTransformerEnd shall have g, g0, b and b0 values corresponding to the no load losses distributed on the three PowerTransformerEnds. The total no load loss shunt impedances may also be placed at one of the PowerTransformerEnds, preferably the end numbered 1, having the shunt values on end 1. This is the preferred way.

4) for a PowerTransformer with more than three Terminals the PowerTransformerEnd impedance values cannot be used. Instead use the TransformerMeshImpedance or split the transformer into multiple PowerTransformers.

Each PowerTransformerEnd must be contained by a PowerTransformer. Because a PowerTransformerEnd (or any other object) can not be contained by more than one parent, a PowerTransformerEnd can not have an association to an EquipmentContainer (Substation, VoltageLevel, etc).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|0..1
|<<merged_ontology-Susceptance,Susceptance>>
|
Magnetizing branch susceptance (B mag). The value can be positive or negative.

|connectionKind (enumeration)
|0..1
|<<merged_ontology-WindingConnection,WindingConnection>>
|
Kind of connection.

|g
|0..1
|<<merged_ontology-Conductance,Conductance>>
|
Magnetizing branch conductance.

|phaseAngleClock
|0..1
|<<merged_ontology-Integer,Integer>>
|
Terminal voltage phase angle displacement where 360 degrees are represented with clock hours. The valid values are 0 to 11. For example, for the secondary side end of a transformer with vector group code of 'Dyn11', specify the connection kind as wye with neutral and specify the phase angle of the clock as 11. The clock value of the transformer end number specified as 1, is assumed to be zero. Note the transformer end number is not assumed to be the same as the terminal sequence number.

|r
|1..1
|<<merged_ontology-Resistance,Resistance>>
|
Resistance (star-model) of the transformer end.

The attribute shall be equal to or greater than zero for non-equivalent transformers.

|ratedS
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Normal apparent power rating.

The attribute shall be a positive value. For a two-winding transformer the values for the high and low voltage sides shall be identical.

|ratedU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Rated voltage: phase-phase for three-phase windings, and either phase-phase or phase-neutral for single-phase windings.

A high voltage side, as given by TransformerEnd.endNumber, shall have a ratedU that is greater than or equal to ratedU for the lower voltage sides.

The attribute shall be a positive value.

|x
|0..1
|<<merged_ontology-Reactance,Reactance>>
|
Positive sequence series reactance (star-model) of the transformer end.

|PowerTransformer
|1..1
|<<merged_ontology-PowerTransformer,PowerTransformer>>
|
The power transformer of this power transformer end.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|endNumber
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|grounded
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|rground
|0..1
|<<merged_ontology-Resistance,Resistance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|xground
|0..1
|<<merged_ontology-Reactance,Reactance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|CoreAdmittance
|0..1
|<<merged_ontology-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|Terminal
|1..1
|<<merged_ontology-Terminal,Terminal>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerTransformerEnd:

[[merged_ontology-RatioTapChanger]]
==== RatioTapChanger

Inheritance path = <<merged_ontology-TapChanger,TapChanger>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:RatioTapChanger:
A tap changer that changes the voltage ratio impacting the voltage magnitude but not the phase angle across the transformer.

Angle sign convention (general): Positive value indicates a positive phase shift from the winding where the tap is located to the other winding (for a two-winding transformer).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|stepVoltageIncrement
|0..1
|<<merged_ontology-PerCent,PerCent>>
|
Tap step increment, in per cent of rated voltage of the power transformer end, per step position.

When the increment is negative, the voltage decreases when the tap step increases.

|TransformerEnd
|1..1
|<<merged_ontology-TransformerEnd,TransformerEnd>>
|
Transformer end to which this ratio tap changer belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|controlEnabled
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-TapChanger,TapChanger>>
|[extension]#ctRating#
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-TapChanger,TapChanger>>
|ctRatio
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-TapChanger,TapChanger>>
|highStep
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-TapChanger,TapChanger>>
|initialDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|see <<merged_ontology-TapChanger,TapChanger>>
|lowStep
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-TapChanger,TapChanger>>
|ltcFlag
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-TapChanger,TapChanger>>
|neutralStep
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-TapChanger,TapChanger>>
|neutralU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|see <<merged_ontology-TapChanger,TapChanger>>
|ptRatio
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-TapChanger,TapChanger>>
|subsequentDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|see <<merged_ontology-TapChanger,TapChanger>>
|TapChangerControl
|0..1
|<<merged_ontology-TapChangerControl,TapChangerControl>>
|see <<merged_ontology-TapChanger,TapChanger>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!RatioTapChanger:

[[merged_ontology-Recloser]]
==== (Description) Recloser

Inheritance path = <<merged_ontology-ProtectedSwitch,ProtectedSwitch>> => <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Recloser,Recloser>>.
endif::merged_ontology-description-profile[]

:Recloser:
Pole-mounted fault interrupter with built-in phase and ground relays, current transformer (CT), and supplemental controls.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-ProtectedSwitch,ProtectedSwitch>>
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Recloser:

[[merged_ontology-Sectionaliser]]
==== (Description) Sectionaliser

Inheritance path = <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Sectionaliser,Sectionaliser>>.
endif::merged_ontology-description-profile[]

:Sectionaliser:
Automatic switch that will lock open to isolate a faulted section. It may, or may not, have load breaking capability. Its primary purpose is to provide fault sectionalising at locations where the fault current is either too high, or too low, for proper coordination of fuses.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Sectionaliser:

[[merged_ontology-SeriesCompensator]]
==== (Description) SeriesCompensator

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-SeriesCompensator,SeriesCompensator>>.
endif::merged_ontology-description-profile[]

:SeriesCompensator:
A Series Compensator is a series capacitor or reactor or an AC transmission line without charging susceptance. It is a two terminal device.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!SeriesCompensator:

[[merged_ontology-ShortCircuitTest]]
==== ShortCircuitTest

Inheritance path = <<merged_ontology-TransformerTest,TransformerTest>>

:ShortCircuitTest:
Short-circuit test results determine mesh impedance parameters. They include load losses and leakage impedances. For three-phase windings, the excitation can be a positive sequence (the default) or a zero sequence. There shall be at least one grounded winding.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|energisedEndStep
|0..1
|<<merged_ontology-Integer,Integer>>
|
Tap step number for the energised end of the test pair.

|groundedEndStep
|0..1
|<<merged_ontology-Integer,Integer>>
|
Tap step number for the grounded end of the test pair.

|leakageImpedance
|0..1
|<<merged_ontology-Impedance,Impedance>>
|
Leakage impedance measured from a positive-sequence or single-phase short-circuit test.

|leakageImpedanceZero
|0..1
|<<merged_ontology-Impedance,Impedance>>
|
Leakage impedance measured from a zero-sequence short-circuit test.

|loss
|0..1
|<<merged_ontology-KiloActivePower,KiloActivePower>>
|
Load losses from a positive-sequence or single-phase short-circuit test.

|lossZero
|0..1
|<<merged_ontology-KiloActivePower,KiloActivePower>>
|
Load losses from a zero-sequence short-circuit test.

|EnergisedEnd
|1..1
|<<merged_ontology-TransformerEndInfo,TransformerEndInfo>>
|
Transformer end that voltage is applied to in this short-circuit test. The test voltage is chosen to induce rated current in the energised end.

|GroundedEnds
|1..*
|<<merged_ontology-TransformerEndInfo,TransformerEndInfo>>
|
All ends short-circuited in this short-circuit test.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|basePower
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|see <<merged_ontology-TransformerTest,TransformerTest>>
|temperature
|1..1
|<<merged_ontology-Temperature,Temperature>>
|see <<merged_ontology-TransformerTest,TransformerTest>>
|===
:!ShortCircuitTest:

[[merged_ontology-Substation]]
==== Substation

Inheritance path = <<merged_ontology-EquipmentContainer,EquipmentContainer>>

:Substation:
A collection of equipment for purposes other than generation or utilization, through which electric energy in bulk is passed for the purposes of switching or modifying its characteristics.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!Substation:

[[merged_ontology-SwitchPhase]]
==== SwitchPhase


:SwitchPhase:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|normalOpen
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Used in cases when no Measurement for the status value is present. If the SwitchPhase has a status measurement the Discrete.normalValue is expected to match with this value.

|phaseSide1 (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase of this SwitchPhase on the side with terminal sequence number equal to 1. Should be a phase contained in that terminal's phases attribute.

|phaseSide2 (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase of this SwitchPhase on the side with terminal sequence number equal to 2. Should be a phase contained in that terminal's Terminal.phases attribute.

|Switch
|1..1
|<<merged_ontology-Switch,Switch>>
|
The switch of the switch phase.

|===
:!SwitchPhase:

[[merged_ontology-SynchronousMachine]]
==== (Description) SynchronousMachine

Inheritance path = <<merged_ontology-RotatingMachine,RotatingMachine>> => <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-SynchronousMachine,SynchronousMachine>>.
endif::merged_ontology-description-profile[]

:SynchronousMachine:
An electromechanical device that operates with shaft rotating synchronously with the network. It is a single machine operating either as a generator or synchronous condenser or pump.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|see <<merged_ontology-RotatingMachine,RotatingMachine>>
|ratedU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|see <<merged_ontology-RotatingMachine,RotatingMachine>>
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!SynchronousMachine:

[[merged_ontology-TapChangerControl]]
==== TapChangerControl

Inheritance path = <<merged_ontology-RegulatingControl,RegulatingControl>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:TapChangerControl:
Describes behaviour specific to tap changers, e.g. how the voltage at the end of a line varies with the load level and compensation of the voltage drop by tap adjustment. When TapChanger.ctRatio and .ptRatio are present, RegulatingControl.targetVoltage RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue, RegulatingControl.minAllowedTargetValue as well as TapChangerControl.maxLimitVoltage and TapChangerControl.minLimitVoltage shall be expressed in terms of secondary CT currents and PT voltages.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|lineDropCompensation
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
If true, the line drop compensation is to be applied.

|lineDropR
|0..1
|<<merged_ontology-Resistance,Resistance>>
|
Line drop compensator resistance setting for normal (forward) power flow.

|lineDropX
|0..1
|<<merged_ontology-Reactance,Reactance>>
|
Line drop compensator reactance setting for normal (forward) power flow.

|maxLimitVoltage
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Maximum allowed regulated voltage on the PT secondary. This is the locally measured secondary voltage, including the effect of any line drop compensation. Typically used for distribution circuit voltage regulator. Sometimes referred to as first-house protection. If utilized, then TapChanger.ptRatio must be supplied.

|minLimitVoltage
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Minimum allowed regulated voltage on the PT secondary. This is the locally measured secondary voltage, including the effect of any line drop compensation. Typically used for distribution circuit voltage regulator. Sometimes referred to as last-house protection. If utilized, then TapChanger.ptRatio must be supplied.

|reverseLineDropR
|0..1
|<<merged_ontology-Resistance,Resistance>>
|
Line drop compensator resistance setting for reverse power flow.

|reverseLineDropX
|0..1
|<<merged_ontology-Reactance,Reactance>>
|
Line drop compensator reactance setting for reverse power flow.

|[extension]#reverseTargetDeadband#
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
|[extension]#reverseTargetValue#
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
|[extension]#reverseToNeutral#
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
|[extension]#reversible#
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
|[extension]#reversingDelay#
|0..1
|<<merged_ontology-Seconds,Seconds>>
|
|[extension]#reversingPowerThreshold#
|0..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|discrete
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|enabled
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|mode (enumeration)
|0..1
|<<merged_ontology-RegulatingControlModeKind,RegulatingControlModeKind>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|monitoredPhase (enumeration)
|0..1
|<<merged_ontology-PhaseCode,PhaseCode>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|targetDeadband
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|targetValue
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|Terminal
|1..1
|<<merged_ontology-Terminal,Terminal>>
|see <<merged_ontology-RegulatingControl,RegulatingControl>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TapChangerControl:

[[merged_ontology-Terminal]]
==== (Description) Terminal

Inheritance path = <<merged_ontology-ACDCTerminal,ACDCTerminal>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-Terminal,Terminal>>.
endif::merged_ontology-description-profile[]

:Terminal:
An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ConductingEquipment
|1..1
|<<merged_ontology-ConductingEquipment,ConductingEquipment>>
|
The conducting equipment of the terminal. Conducting equipment have terminals that may be connected to other conducting equipment terminals via connectivity nodes or topological nodes.

|ConnectivityNode
|1..1
|<<merged_ontology-ConnectivityNode,ConnectivityNode>>
|
The connectivity node to which this terminal connects with zero impedance.

|NormalHeadFeeder
|0..1
|<<merged_ontology-Feeder,Feeder>>
|
The feeder that this terminal normally feeds. Only specified for the terminals at head of feeders.

|TransformerEnd
|0..1
|<<merged_ontology-TransformerEnd,TransformerEnd>>
|
All transformer ends connected at this terminal.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|sequenceNumber
|0..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-ACDCTerminal,ACDCTerminal>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Terminal:

[[merged_ontology-TextDiagramObject]]
==== TextDiagramObject

Inheritance path = <<merged_ontology-DiagramObject,DiagramObject>>

:TextDiagramObject:
A diagram object for placing free-text or text derived from an associated domain object.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|text
|1..1
|<<merged_ontology-String,String>>
|
The text that is displayed by this text diagram object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|drawingOrder
|0..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|isPolygon
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|offsetX
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|offsetY
|0..1
|<<merged_ontology-Float,Float>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|rotation
|0..1
|<<merged_ontology-AngleDegrees,AngleDegrees>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|Diagram
|1..1
|<<merged_ontology-Diagram,Diagram>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|DiagramObjectStyle
|1..1
|<<merged_ontology-DiagramObjectStyle,DiagramObjectStyle>>
|see <<merged_ontology-DiagramObject,DiagramObject>>
|===
:!TextDiagramObject:

[[merged_ontology-ThermalGeneratingUnit]]
==== ThermalGeneratingUnit

Inheritance path = <<merged_ontology-GeneratingUnit,GeneratingUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ThermalGeneratingUnit:
A generating unit whose prime mover could be a steam turbine, combustion turbine, or diesel engine.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|FossilFuels
|0..*
|<<merged_ontology-FossilFuel,FossilFuel>>
|
A thermal generating unit may have one or more fossil fuels.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-GeneratingUnit,GeneratingUnit>>
|RotatingMachine
|1..1
|<<merged_ontology-RotatingMachine,RotatingMachine>>
|see <<merged_ontology-GeneratingUnit,GeneratingUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ThermalGeneratingUnit:

[[merged_ontology-TransformerCoreAdmittance]]
==== TransformerCoreAdmittance

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:TransformerCoreAdmittance:
The transformer core admittance. Used to specify the core admittance of a transformer in a manner that can be shared among power transformers.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|b
|1..1
|<<merged_ontology-Susceptance,Susceptance>>
|
Magnetizing branch susceptance (B mag). The value can be positive or negative.

|g
|1..1
|<<merged_ontology-Conductance,Conductance>>
|
Magnetizing branch conductance (G mag).

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TransformerCoreAdmittance:

[[merged_ontology-TransformerEndInfo]]
==== TransformerEndInfo

Inheritance path = <<merged_ontology-ConductingAssetInfo,ConductingAssetInfo>> => <<merged_ontology-AssetInfo,AssetInfo>>

:TransformerEndInfo:
Transformer end data.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|connectionKind (enumeration)
|0..1
|<<merged_ontology-WindingConnection,WindingConnection>>
|
Kind of connection.

|emergencyS
|0..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Apparent power that the winding can carry under emergency conditions (also called long-term emergency power).

|endNumber
|1..1
|<<merged_ontology-Integer,Integer>>
|
Number for this transformer end, corresponding to the end's order in the PowerTransformer.vectorGroup attribute. Highest voltage winding should be 1.

|insulationU
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
Basic insulation level voltage rating.

|phaseAngleClock
|0..1
|<<merged_ontology-Integer,Integer>>
|
Winding phase angle where 360 degrees are represented with clock hours, so the valid values are {0, ..., 11}. For example, to express the second winding in code 'Dyn11', set attributes as follows: 'endNumber'=2, 'connectionKind' = Yn and 'phaseAngleClock' = 11.

|r
|0..1
|<<merged_ontology-Resistance,Resistance>>
|
DC resistance.

|ratedS
|0..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Normal apparent power rating.

|shortTermS
|0..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Apparent power that this winding can carry for a short period of time (in emergency).

|TransformerTankInfo
|0..1
|<<merged_ontology-TransformerTankInfo,TransformerTankInfo>>
|
Transformer tank data that this end description is part of.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedVoltage
|0..1
|<<merged_ontology-Voltage,Voltage>>
|see <<merged_ontology-ConductingAssetInfo,ConductingAssetInfo>>
|===
:!TransformerEndInfo:

[[merged_ontology-TransformerMeshImpedance]]
==== TransformerMeshImpedance

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:TransformerMeshImpedance:
Transformer mesh impedance (Delta-model) between transformer ends.

The typical case is that this class describes the impedance between two transformer ends pair-wise, i.e. the cardinalities at both transformer end associations are 1. However, in cases where two or more transformer ends are modelled the cardinalities are larger than 1.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|r
|1..1
|<<merged_ontology-Resistance,Resistance>>
|
Resistance between the 'from' and the 'to' end, seen from the 'from' end.

|x
|1..1
|<<merged_ontology-Reactance,Reactance>>
|
Reactance between the 'from' and the 'to' end, seen from the 'from' end.

|FromTransformerEnd
|0..1
|<<merged_ontology-TransformerEnd,TransformerEnd>>
|
From end this mesh impedance is connected to. It determines the voltage reference.

|ToTransformerEnd
|0..*
|<<merged_ontology-TransformerEnd,TransformerEnd>>
|
All transformer ends this mesh impedance is connected to.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TransformerMeshImpedance:

[[merged_ontology-TransformerTank]]
==== (Description) TransformerTank

Inheritance path = <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-TransformerTank,TransformerTank>>.
endif::merged_ontology-description-profile[]

:TransformerTank:
An assembly of two or more coupled windings that transform electrical power between voltage levels. These windings are bound on a common core and placed in the same tank. Transformer tank can be used to model both single-phase and 3-phase transformers.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|PowerTransformer
|1..1
|<<merged_ontology-PowerTransformer,PowerTransformer>>
|
Bank this transformer belongs to.

|TransformerTankEnds
|1..*
|<<merged_ontology-TransformerTankEnd,TransformerTankEnd>>
|
All windings of this transformer.

|[extension]#TransformerTankInfo#
|0..1
|<<merged_ontology-TransformerTankInfo,TransformerTankInfo>>
|
|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TransformerTank:

[[merged_ontology-TransformerTankEnd]]
==== (Description) TransformerTankEnd

Inheritance path = <<merged_ontology-TransformerEnd,TransformerEnd>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

ifdef::merged_ontology-description-profile[]
This class is tagged in this profile with the 'Description' tag. To refer to the full definition of this class as defined in the profile this one depends on visit <<{merged_ontology-description-profile}-TransformerTankEnd,TransformerTankEnd>>.
endif::merged_ontology-description-profile[]

:TransformerTankEnd:
Transformer tank end represents an individual winding for unbalanced models or for transformer tanks connected into a bank (and bank is modelled with the PowerTransformer).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|[extension]#orderedPhases (enumeration, gmdm)#
|1..1
|<<merged_ontology-OrderedPhaseCodeKind,OrderedPhaseCodeKind>>
|
|TransformerTank
|1..1
|<<merged_ontology-TransformerTank,TransformerTank>>
|
Transformer this winding belongs to.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|endNumber
|1..1
|<<merged_ontology-Integer,Integer>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|grounded
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|rground
|0..1
|<<merged_ontology-Resistance,Resistance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|xground
|0..1
|<<merged_ontology-Reactance,Reactance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|CoreAdmittance
|0..1
|<<merged_ontology-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|Terminal
|1..1
|<<merged_ontology-Terminal,Terminal>>
|see <<merged_ontology-TransformerEnd,TransformerEnd>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TransformerTankEnd:

[[merged_ontology-TransformerTankInfo]]
==== TransformerTankInfo

Inheritance path = <<merged_ontology-AssetInfo,AssetInfo>>

:TransformerTankInfo:
Set of transformer tank data, from an equipment library.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!TransformerTankInfo:

[[merged_ontology-VisibilityLayer]]
==== VisibilityLayer


:VisibilityLayer:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|drawingOrder
|0..1
|<<merged_ontology-Integer,Integer>>
|
The drawing order for this layer. The higher the number, the later the layer and the objects within it are rendered.

|VisibleObjects
|0..*
|<<merged_ontology-DiagramObject,DiagramObject>>
|
A visibility layer can contain one or more diagram objects.

|===
:!VisibilityLayer:

[[merged_ontology-VoltageLevel]]
==== VoltageLevel

Inheritance path = <<merged_ontology-EquipmentContainer,EquipmentContainer>>

:VoltageLevel:
A collection of equipment at one common system voltage forming a switchgear. The equipment typically consists of breakers, busbars, instrumentation, control, regulation and protection devices as well as assemblies of all these.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|
The base voltage used for all equipment within the voltage level.

|Substation (OfAggregate)
|1..1
|<<merged_ontology-Substation,Substation>>
|
The substation of the voltage level.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!VoltageLevel:

[[merged_ontology-WindGeneratingUnit]]
==== WindGeneratingUnit

Inheritance path = <<merged_ontology-GeneratingUnit,GeneratingUnit>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:WindGeneratingUnit:
A wind driven generating unit, connected to the grid by means of a rotating machine. May be used to represent a single turbine or an aggregation.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|windGenUnitType (enumeration)
|0..1
|<<merged_ontology-WindGenUnitKind,WindGenUnitKind>>
|
The kind of wind generating unit.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<merged_ontology-ActivePower,ActivePower>>
|see <<merged_ontology-GeneratingUnit,GeneratingUnit>>
|RotatingMachine
|1..1
|<<merged_ontology-RotatingMachine,RotatingMachine>>
|see <<merged_ontology-GeneratingUnit,GeneratingUnit>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!WindGeneratingUnit:


=== Abstract Classes

[[merged_ontology-ACDCTerminal]]
==== ACDCTerminal

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ACDCTerminal:
An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|sequenceNumber
|0..1
|<<merged_ontology-Integer,Integer>>
|
The orientation of the terminal connections for a multiple terminal conducting equipment. The sequence numbering starts with 1 and additional terminals should follow in increasing order. The first terminal is the "starting point" for a two terminal branch.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ACDCTerminal:

[[merged_ontology-AssetInfo]]
==== AssetInfo


:AssetInfo:
Set of attributes of an asset, representing typical datasheet information of a physical device that can be instantiated and shared in different data exchange contexts:

- as attributes of an asset instance (installed or in stock)

- as attributes of an asset model (product by a manufacturer)

- as attributes of a type asset (generic type of an asset as used in designs/extension planning).

:!AssetInfo:

[[merged_ontology-ConductingAssetInfo]]
==== ConductingAssetInfo

Inheritance path = <<merged_ontology-AssetInfo,AssetInfo>>

:ConductingAssetInfo:
Generic information for conducting asset


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedVoltage
|0..1
|<<merged_ontology-Voltage,Voltage>>
|
Rated voltage.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|===
:!ConductingAssetInfo:

[[merged_ontology-ConductingEquipment]]
==== ConductingEquipment

Inheritance path = <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ConductingEquipment:
The parts of the AC power system that are designed to carry current or that are conductively connected through terminals.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|
Base voltage of this conducting equipment. Use only when there is no voltage level container used and only one base voltage applies. For example, not used for transformers.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ConductingEquipment:

[[merged_ontology-Conductor]]
==== Conductor

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:Conductor:
Combination of conducting material with consistent electrical characteristics, building a single electrical system, used to carry current between points in the power system.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|length
|1..1
|<<merged_ontology-Length,Length>>
|
Segment length for calculating line segment capabilities.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Conductor:

[[merged_ontology-ConnectivityNodeContainer]]
==== ConnectivityNodeContainer

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ConnectivityNodeContainer:
A base class for all objects that may contain connectivity nodes or topological nodes.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ConnectivityNodeContainer:

[[merged_ontology-Connector]]
==== Connector

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:Connector:
A conductor, or group of conductors, with negligible impedance, that serve to connect other conducting equipment within a single substation and are modelled with a single logical terminal.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Connector:

[[merged_ontology-EnergyConnection]]
==== EnergyConnection

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:EnergyConnection:
A connection of energy generation or consumption on the power system model.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!EnergyConnection:

[[merged_ontology-Equipment]]
==== Equipment

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:Equipment:
The parts of a power system that are physical devices, electronic or mechanical.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
The aggregate flag provides an alternative way of representing an aggregated (equivalent) element. It is applicable in cases when the dedicated classes for equivalent equipment do not have all of the attributes necessary to represent the required level of detail. In case the flag is set to "true" the single instance of equipment represents multiple pieces of equipment that have been modelled together as an aggregate equivalent obtained by a network reduction procedure. Examples would be power transformers or synchronous machines operating in parallel modelled as a single aggregate power transformer or aggregate synchronous machine.

The attribute is not used for EquivalentBranch, EquivalentShunt, EquivalentInjection and ExternalNetworkInjection.

|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Specifies the availability of the equipment under normal operating conditions. True means the equipment is available for topology processing, which determines if the equipment is energized or not. False means that the equipment is treated by network applications as if it is not in the model.

|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|
Additional equipment container beyond the primary equipment container. The equipment is contained in another equipment container, but also grouped with this equipment container.

|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|
Container of this equipment.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Equipment:

[[merged_ontology-EquipmentContainer]]
==== EquipmentContainer


:EquipmentContainer:
A modelling construct to provide a root class for containing equipment.

ifdef::merged_ontology-byref-profile[]
This abstract class serves as a 'By Reference' association within this profile and as such has no attributes or associations defined. Rather, it is used to reference a corresponding concrete class defined in an external profile that this one depends upon. To reference this definition in that profile visit <<{merged_ontology-byref-profile}-EquipmentContainer,EquipmentContainer>>.

endif::merged_ontology-byref-profile[]
ifndef::merged_ontology-byref-profile[]
This abstract class serves as a 'By Reference' association within this profile and as such has no attributes or associations defined. Rather, it is used to reference a corresponding concrete class defined in an external profile that this one depends upon.

endif::merged_ontology-byref-profile[]
:!EquipmentContainer:

[[merged_ontology-GeneratingUnit]]
==== GeneratingUnit

Inheritance path = <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:GeneratingUnit:
A single or set of synchronous machines for converting mechanical power into alternating-current power. For example, individual machines within a set may be defined for scheduling purposes while a single control signal is derived for the set. In this case there would be a GeneratingUnit for each member of the set and an additional GeneratingUnit corresponding to the set.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedGrossMaxP
|0..1
|<<merged_ontology-ActivePower,ActivePower>>
|
The unit's gross rated maximum capacity (book value).

The attribute shall be a positive value.

|RotatingMachine
|1..1
|<<merged_ontology-RotatingMachine,RotatingMachine>>
|
A synchronous machine may operate as a generator and as such becomes a member of a generating unit.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!GeneratingUnit:

[[merged_ontology-IdentifiedObject]]
==== IdentifiedObject

Inheritance path = <<merged_ontology-Identity,Identity>>

:IdentifiedObject:
This is a class that provides common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|
The description is a free human readable text describing or naming the object. It may be non unique and may not correlate to a naming hierarchy.

|name
|0..1
|<<merged_ontology-String,String>>
|
The name is any free human readable and possibly non unique text naming the object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!IdentifiedObject:

[[merged_ontology-Identity]]
==== Identity


:Identity:
,


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|identifier
|1..1
|<<merged_ontology-String,String>>
|
A universally unique object identifier. Used to uniquely identify persistent objects between CIM messages.

|===
:!Identity:

[[merged_ontology-Name]]
==== Name


:Name:
The Name class, in possible combination with a name type and a naming authority provides the means to define any number of names or alternative identifiers for an object.

:!Name:

[[merged_ontology-PerLengthImpedance]]
==== PerLengthImpedance

Inheritance path = <<merged_ontology-PerLengthLineParameter,PerLengthLineParameter>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PerLengthImpedance:
Common type for per-length electrical impedances.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PerLengthImpedance:

[[merged_ontology-PerLengthLineParameter]]
==== PerLengthLineParameter

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PerLengthLineParameter:
Common type for per-length electrical line parameters.


*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PerLengthLineParameter:

[[merged_ontology-Pnode]]
==== Pnode


:Pnode:
ifdef::merged_ontology-byref-profile[]
This abstract class serves as a 'By Reference' association within this profile and as such has no attributes or associations defined. Rather, it is used to reference a corresponding concrete class defined in an external profile that this one depends upon. To reference this definition in that profile visit <<{merged_ontology-byref-profile}-Pnode,Pnode>>.

endif::merged_ontology-byref-profile[]
ifndef::merged_ontology-byref-profile[]
This abstract class serves as a 'By Reference' association within this profile and as such has no attributes or associations defined. Rather, it is used to reference a corresponding concrete class defined in an external profile that this one depends upon.

endif::merged_ontology-byref-profile[]
:!Pnode:

[[merged_ontology-PowerElectronicsUnit]]
==== PowerElectronicsUnit

Inheritance path = <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PowerElectronicsUnit:
A generating unit or battery or aggregation that connects to the AC network using power electronics rather than rotating machines.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maxP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|
Maximum active power limit. This is the maximum (nameplate) limit for the unit.

|minP
|1..1
|<<merged_ontology-ActivePower,ActivePower>>
|
Minimum active power limit. This is the minimum (nameplate) limit for the unit.

|PowerElectronicsConnection
|1..1
|<<merged_ontology-PowerElectronicsConnection,PowerElectronicsConnection>>
|
A power electronics unit has a connection to the AC network.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerElectronicsUnit:

[[merged_ontology-PowerSystemResource]]
==== PowerSystemResource

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:PowerSystemResource:
A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|
Location of this power system resource.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!PowerSystemResource:

[[merged_ontology-ProtectedSwitch]]
==== ProtectedSwitch

Inheritance path = <<merged_ontology-Switch,Switch>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ProtectedSwitch:
A ProtectedSwitch is a switching device that can be operated by ProtectionEquipment.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|breakingCapacity
|0..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|
The maximum fault current a breaking device can break safely under prescribed conditions of use.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Switch,Switch>>
|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|see <<merged_ontology-Switch,Switch>>
|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|see <<merged_ontology-Switch,Switch>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ProtectedSwitch:

[[merged_ontology-RegulatingCondEq]]
==== RegulatingCondEq

Inheritance path = <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:RegulatingCondEq:
A type of conducting equipment that can regulate a quantity (i.e. voltage or flow) at a specific point in the network.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|
The regulating control scheme in which this equipment participates.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!RegulatingCondEq:

[[merged_ontology-RegulatingControl]]
==== RegulatingControl

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:RegulatingControl:
Specifies a set of equipment that works together to control a power system quantity such as voltage or flow.

Remote bus voltage control is possible by specifying the controlled terminal located at some place remote from the controlling equipment.

The specified terminal shall be associated with the connectivity node of the controlled point. The most specific subtype of RegulatingControl shall be used in case such equipment participate in the control, e.g. TapChangerControl for tap changers.

For flow control, load sign convention is used, i.e. positive sign means flow out from a TopologicalNode (bus) into the conducting equipment.

The attribute minAllowedTargetValue and maxAllowedTargetValue are required in the following cases:

- For a power generating module operated in power factor control mode to specify maximum and minimum power factor values;

- Whenever it is necessary to have an off center target voltage for the tap changer regulator. For instance, due to long cables to off shore wind farms and the need to have a simpler setup at the off shore transformer platform, the voltage is controlled from the land at the connection point for the off shore wind farm. Since there usually is a voltage rise along the cable, there is typical and overvoltage of up 3 to 4 kV compared to the on shore station. Thus in normal operation the tap changer on the on shore station is operated with a target set point, which is in the lower parts of the dead band.

The attributes minAllowedTargetValue and maxAllowedTargetValue are not related to the attribute targetDeadband and thus they are not treated as an alternative of the targetDeadband. They are needed due to limitations in the local substation controller. The attribute targetDeadband is used to prevent the power flow from moving the tap position in circles (hunting) that is to be used regardless of the attributes minAllowedTargetValue and maxAllowedTargetValue.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|discrete
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
If true, indicates that regulation is performed in the simulation in a discrete mode. If false, indicates that non-discrete regulation is used in the simulation. This applies to equipment with discrete controls, e.g. tap changers and shunt compensators.

|enabled
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
The flag tells if regulation is enabled.

|mode (enumeration)
|0..1
|<<merged_ontology-RegulatingControlModeKind,RegulatingControlModeKind>>
|
The regulating control mode presently available. This specification allows for determining the kind of regulation without need for obtaining the units from a schedule.

|monitoredPhase (enumeration)
|0..1
|<<merged_ontology-PhaseCode,PhaseCode>>
|
Phase voltage controlling this regulator, measured at regulator location.

|targetDeadband
|0..1
|<<merged_ontology-Float,Float>>
|
This is the deadband set on the controller. It is used with discrete control to avoid excessive tap changes in tap changers and state changes in shunt compensator banks while regulating. The units in which deadband is expressed are based on RegulatingControl.mode. The attribute shall be a positive value or zero. If RegulatingControl.discrete is set to "false", the RegulatingControl.targetDeadband is to be ignored in simulations. If TapChanger.ctRatio or TapChanger.ptRatio are populated, deadband shall be expressed in secondary units.

Note that for instance, if the targetValue is 100 kV and the targetDeadband is 2 kV the range is from 99 to 101 kV.

|targetValue
|0..1
|<<merged_ontology-Float,Float>>
|
The target value set on the controller. It is the starting value for a steady state solution. This value can be used for the target value without the use of schedules. The value has the units appropriate to the mode attribute.

If used for a TapChangerControl and if TapChanger.ctRatio or TapChanger.ptRatio are populated, the target value shall be expressed in secondary units. As an example, with PT ratio of 60 on a 12.47 KV distribution system, a phase to ground PT has a ratio of 7200 volts primary to 120 volts secondary. If the required primary target is 7128 volts for a single phase tap changer then the value of targetValue would equal 118.8 volts secondary (7128/60).

|Terminal
|1..1
|<<merged_ontology-Terminal,Terminal>>
|
The terminal associated with this regulating control. The terminal is associated instead of a node, since the terminal could connect into either a topological node or a connectivity node. Sometimes it is useful to model regulation at a terminal of a bus bar object.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!RegulatingControl:

[[merged_ontology-RotatingMachine]]
==== RotatingMachine

Inheritance path = <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:RotatingMachine:
A rotating machine which may be used as a generator or motor.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|ratedS
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Nameplate apparent power rating for the unit.

The attribute shall have a positive value.

|ratedU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Rated voltage (nameplate data, Ur in IEC 60909-0). It is primarily used for short circuit data exchange according to IEC 60909.

The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!RotatingMachine:

[[merged_ontology-ShuntCompensator]]
==== ShuntCompensator

Inheritance path = <<merged_ontology-RegulatingCondEq,RegulatingCondEq>> => <<merged_ontology-EnergyConnection,EnergyConnection>> => <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ShuntCompensator:
A shunt capacitor or reactor or switchable bank of shunt capacitors or reactors. A section of a shunt compensator is an individual capacitor or reactor. A negative value for bPerSection indicates that the compensator is a reactor. ShuntCompensator is a single terminal device. Ground is implied.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|aVRDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|
An automatic voltage regulation delay (AVRDelay) which is the time delay from a change in voltage to when the capacitor is allowed to change state. This filters out temporary changes in voltage.

|grounded
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
Required for Yn and I connections (as represented by ShuntCompensator.phaseConnection). True if the neutral is solidly grounded.

|maximumSections
|1..1
|<<merged_ontology-Integer,Integer>>
|
The maximum number of sections that may be switched in.

|nomU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
The voltage at which the nominal reactive power may be calculated. This should normally be within 10% of the voltage at which the capacitor is connected to the network.

|normalSections
|1..1
|<<merged_ontology-Integer,Integer>>
|
The normal number of sections switched in. The value shall be between zero and ShuntCompensator.maximumSections.

|phaseConnection (enumeration)
|0..1
|<<merged_ontology-PhaseShuntConnectionKind,PhaseShuntConnectionKind>>
|
The type of phase connection, such as wye or delta.

|ShuntCompensatorPhase
|0..*
|<<merged_ontology-ShuntCompensatorPhase,ShuntCompensatorPhase>>
|
The individual phases models for the shunt compensator.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|RegulatingControl
|0..1
|<<merged_ontology-RegulatingControl,RegulatingControl>>
|see <<merged_ontology-RegulatingCondEq,RegulatingCondEq>>
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ShuntCompensator:

[[merged_ontology-ShuntCompensatorPhase]]
==== ShuntCompensatorPhase

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:ShuntCompensatorPhase:
Single phase of a multi-phase shunt compensator when its attributes might be different per phase.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|maximumSections
|1..1
|<<merged_ontology-Integer,Integer>>
|
The maximum number of sections that may be switched in for this phase.

|normalSections
|1..1
|<<merged_ontology-Integer,Integer>>
|
For the capacitor phase, the normal number of sections switched in. The value shall be between zero and ShuntCompensatorPhase.maximumSections.

|phase (enumeration)
|1..1
|<<merged_ontology-SinglePhaseKind,SinglePhaseKind>>
|
Phase of this shunt compensator component. If the shunt compensator is wye connected, the connection is from the indicated phase to the central ground or neutral point. If the shunt compensator is delta connected, the phase indicates a shunt compensator connected from the indicated phase to the next logical non-neutral phase.

|ShuntCompensator
|1..1
|<<merged_ontology-ShuntCompensator,ShuntCompensator>>
|
Shunt compensator of this shunt compensator phase.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!ShuntCompensatorPhase:

[[merged_ontology-Switch]]
==== Switch

Inheritance path = <<merged_ontology-ConductingEquipment,ConductingEquipment>> => <<merged_ontology-Equipment,Equipment>> => <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:Switch:
A generic device designed to close, or open, or both, one or more electric circuits. All switches are two terminal devices including grounding switches. The ACDCTerminal.connected at the two sides of the switch shall not be considered for assessing switch connectivity, i.e. only Switch.open, .normalOpen and .locked are relevant.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|locked
|0..1
|<<merged_ontology-Boolean,Boolean>>
|
If true, the switch is locked. The resulting switch state is a combination of locked and Switch.open attributes as follows:

<ul>

<li>locked=true and Switch.open=true. The resulting state is open and locked;</li>

<li>locked=false and Switch.open=true. The resulting state is open;</li>

<li>locked=false and Switch.open=false. The resulting state is closed.</li>

</ul>

|normalOpen
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
The attribute is used in cases when no Measurement for the status value is present. If the Switch has a status measurement the Discrete.normalValue is expected to match with the Switch.normalOpen.

|ratedCurrent
|1..1
|<<merged_ontology-CurrentFlow,CurrentFlow>>
|
The maximum continuous current carrying capacity in amps governed by the device material and construction.

The attribute shall be a positive value.

|SwitchPhase
|0..*
|<<merged_ontology-SwitchPhase,SwitchPhase>>
|
The individual switch phases for the switch.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|see <<merged_ontology-ConductingEquipment,ConductingEquipment>>
|aggregate
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|normallyInService
|0..1
|<<merged_ontology-Boolean,Boolean>>
|see <<merged_ontology-Equipment,Equipment>>
|AdditionalEquipmentContainer
|0..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|EquipmentContainer
|1..1
|<<merged_ontology-EquipmentContainer,EquipmentContainer>>
|see <<merged_ontology-Equipment,Equipment>>
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!Switch:

[[merged_ontology-TapChanger]]
==== TapChanger

Inheritance path = <<merged_ontology-PowerSystemResource,PowerSystemResource>> => <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:TapChanger:
Mechanism for changing transformer winding tap positions.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|controlEnabled
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
Specifies the regulation status of the equipment. True is regulating, false is not regulating.

|[extension]#ctRating#
|0..1
|<<merged_ontology-Float,Float>>
|
|ctRatio
|0..1
|<<merged_ontology-Float,Float>>
|
Built-in current transformer ratio. If a value is specified, then RegulatingControl.targetValue (and RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue and RegulatingControl.minAllowedTargetValue) are expressed in secondary units.

|highStep
|1..1
|<<merged_ontology-Integer,Integer>>
|
Highest possible tap step position, advance from neutral.

The attribute shall be greater than lowStep.

|initialDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|
For an LTC, the delay for initial tap changer operation (first step change).

|lowStep
|1..1
|<<merged_ontology-Integer,Integer>>
|
Lowest possible tap step position, retard from neutral.

|ltcFlag
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
Specifies whether or not a TapChanger has load tap changing capabilities.

|neutralStep
|1..1
|<<merged_ontology-Integer,Integer>>
|
The neutral tap step position for this winding.

The attribute shall be equal to or greater than lowStep and equal or less than highStep.

It is the step position where the voltage is neutralU when the other terminals of the transformer are at the ratedU. If there are other tap changers on the transformer those taps are kept constant at their neutralStep.

|neutralU
|1..1
|<<merged_ontology-Voltage,Voltage>>
|
Voltage at which the winding operates at the neutral tap setting. It is the voltage at the terminal of the PowerTransformerEnd associated with the tap changer when all tap changers on the transformer are at their neutralStep position. Normally neutralU of the tap changer is the same as ratedU of the PowerTransformerEnd, but it can differ in special cases such as when the tapping mechanism is separate from the winding more common on lower voltage transformers.

This attribute is not relevant for PhaseTapChangerAsymmetrical, PhaseTapChangerSymmetrical and PhaseTapChangerLinear.

|ptRatio
|0..1
|<<merged_ontology-Float,Float>>
|
Built-in potential (voltage) transformer ratio. If a value is specified, then RegulatingControl.targetValue (and RegulatingControl.targetDeadband, RegulatingControl.maxAllowedTargetValue, RegulatingControl.minAllowedTargetValue as well as TapChangerControl.maxLimitVoltage and TapChangerControl.minLimitVoltage) are expressed in secondary units.

|subsequentDelay
|0..1
|<<merged_ontology-Seconds,Seconds>>
|
For an LTC, the delay for subsequent tap changer operation (second and later step changes).

|TapChangerControl
|0..1
|<<merged_ontology-TapChangerControl,TapChangerControl>>
|
The regulating control scheme in which this tap changer participates.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|Location
|0..1
|<<merged_ontology-Location,Location>>
|see <<merged_ontology-PowerSystemResource,PowerSystemResource>>
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TapChanger:

[[merged_ontology-TransformerEnd]]
==== TransformerEnd

Inheritance path = <<merged_ontology-IdentifiedObject,IdentifiedObject>> => <<merged_ontology-Identity,Identity>>

:TransformerEnd:
A conducting connection point of a power transformer. It corresponds to a physical transformer winding terminal. In earlier CIM versions, the TransformerWinding class served a similar purpose, but this class is more flexible because it associates to terminal but is not a specialization of ConductingEquipment.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|endNumber
|1..1
|<<merged_ontology-Integer,Integer>>
|
Number for this transformer end, corresponding to the end's order in the power transformer vector group or phase angle clock number. Highest voltage winding should be 1. Each end within a power transformer should have a unique subsequent end number. Note the transformer end number need not match the terminal sequence number.

|grounded
|1..1
|<<merged_ontology-Boolean,Boolean>>
|
Used only for Yn and Zn connections indicated by PowerTransformerEnd.connectionKind. If true, the neutral is grounded and attributes TransformerEnd.rground and TransformerEnd.xground are required. If false, the attributes TransformerEnd.rground and TransformerEnd.xground are not considered.

|rground
|0..1
|<<merged_ontology-Resistance,Resistance>>
|
Resistance part of neutral impedance. Zero indicates solidly grounded or grounded through a reactor.

|xground
|0..1
|<<merged_ontology-Reactance,Reactance>>
|
Reactance part of neutral impedance. Zero indicates solidly grounded or grounded through a reactor.

|BaseVoltage
|1..1
|<<merged_ontology-BaseVoltage,BaseVoltage>>
|
Base voltage of the transformer end. This is essential for PU calculation.

|CoreAdmittance
|0..1
|<<merged_ontology-TransformerCoreAdmittance,TransformerCoreAdmittance>>
|
Core admittance of this transformer end, representing magnetising current and core losses. The full values of the transformer should be supplied for one transformer end only.

|Terminal
|1..1
|<<merged_ontology-Terminal,Terminal>>
|
Terminal of the power transformer to which this transformer end belongs.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|description
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|name
|0..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-IdentifiedObject,IdentifiedObject>>
|identifier
|1..1
|<<merged_ontology-String,String>>
|see <<merged_ontology-Identity,Identity>>
|===
:!TransformerEnd:

[[merged_ontology-TransformerTest]]
==== TransformerTest


:TransformerTest:

*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%a"]
|===
|name |mult |type |description
|basePower
|1..1
|<<merged_ontology-ApparentPower,ApparentPower>>
|
Base power at which the tests are conducted, usually equal to the rateds of one of the involved transformer ends.

|temperature
|1..1
|<<merged_ontology-Temperature,Temperature>>
|
Temperature at which the test is conducted.

|===
:!TransformerTest:


=== Enumerations

[[merged_ontology-ConverterControlModeKind]]
==== ConverterControlModeKind


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|constantPowerFactor
|

|constantReactivePower
|

|dynamic
|
|===
[[merged_ontology-FuelType]]
==== FuelType

Type of fuel.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|brownCoalLignite
|
Brown coal lignite.


|coal
|
Generic coal, not including lignite type.


|coalDerivedGas
|
Coal derived gas.


|diesel
|
Diesel


|gas
|
Natural gas.


|hardCoal
|
Hard coal.


|lignite
|
The fuel is lignite coal. Note that this is a special type of coal, so the other enum of coal is reserved for hard coal types or if the exact type of coal is not known.


|oil
|
Oil.


|oilShale
|
Oil Shale.


|other
|
Any fuel type not included in the rest of the enumerated value.


|peat
|
Peat.

|===
[[merged_ontology-OrderedPhaseCodeKind]]
==== OrderedPhaseCodeKind

In some use cases, the ordering of phases is important. The PhaseCode class does not represent order, but this class addresses such use cases. When two or more phases are present, the individual phases may occur in any order, but the neutral must always occur last. When only one phase and the neutral is present, that phase and the neutral may be re-ordered.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|A
|

|AB
|

|ABC
|

|ABCN
|

|ABN
|

|AC
|

|ACB
|

|ACBN
|

|ACN
|

|AN
|

|B
|

|BA
|

|BAC
|

|BACN
|

|BAN
|

|BC
|

|BCA
|

|BCAN
|

|BCN
|

|BN
|

|C
|

|CA
|

|CAB
|

|CABN
|

|CAN
|

|CB
|

|CBA
|

|CBAN
|

|CBN
|

|CN
|

|NA
|

|NB
|

|NC
|

|Ns1
|

|Ns2
|

|X
|

|XN
|

|XY
|

|XYN
|

|none
|

|s1
|

|s12
|

|s12N
|

|s1N
|

|s2
|

|s21
|

|s21N
|

|s2N
|
|===
[[merged_ontology-OrientationKind]]
==== OrientationKind

The orientation of the coordinate system with respect to top, left, and the coordinate number system.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|negative
|
For 2D diagrams, a negative orientation gives the left-hand orientation (favoured by computer graphics displays) with X values increasing from left to right and Y values increasing from top to bottom. This is also known as a left hand orientation.


|positive
|
For 2D diagrams, a positive orientation will result in X values increasing from left to right and Y values increasing from bottom to top. This is also known as a right hand orientation.

|===
[[merged_ontology-PhaseCode]]
==== PhaseCode

Enumeration of phase identifiers used to designate the combination of phase and/or neutral conductors at a terminal, measurement or equipment modelled as a single-line balanced equivalent.

This is an unordered enumeration of phase identifiers. Allows designation of phases for both transmission and distribution equipment, circuits and loads. The enumeration, by itself, does not describe how the phases are connected together or connected to ground. Ground is not explicitly denoted as a phase.

Residential and small commercial loads are often served from single-phase, or split-phase, secondary circuits. For the example of s12N, phases 1 and 2 refer to hot wires that are 180 degrees out of phase, while N refers to the neutral wire. Through single-phase transformer connections, these secondary circuits may be served from one or two of the primary phases A, B, and C. For three-phase loads, use the A, B, C phase codes instead of s12N.

The integer values are from IEC 61968-9 to support revenue metering applications.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|A
|
Phase A.


|AB
|
Phases A and B.


|ABC
|
Phases A, B, and C.


|ABCN
|
Phases A, B, C, and N.


|ABN
|
Phases A, B, and neutral.


|AC
|
Phases A and C.


|ACN
|
Phases A, C and neutral.


|AN
|
Phases A and neutral.


|B
|
Phase B.


|BC
|
Phases B and C.


|BCN
|
Phases B, C, and neutral.


|BN
|
Phases B and neutral.


|C
|
Phase C.


|CN
|
Phases C and neutral.


|N
|
Neutral phase.


|X
|
Unknown non-neutral phase.


|XN
|
Unknown non-neutral phase plus neutral.


|XY
|
Two unknown non-neutral phases.


|XYN
|
Two unknown non-neutral phases plus neutral.


|none
|
No phases specified.


|s1
|
Secondary phase 1.


|s12
|
Secondary phase 1 and 2.


|s12N
|
Secondary phases 1, 2, and neutral.


|s1N
|
Secondary phase 1 and neutral.


|s2
|
Secondary phase 2.


|s2N
|
Secondary phase 2 and neutral.

|===
[[merged_ontology-PhaseCountKind]]
==== PhaseCountKind

Number of phases supported by a device.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|other
|
Other


|singlePhase
|
Single phase


|threePhase
|
Three phases

|===
[[merged_ontology-PhaseShuntConnectionKind]]
==== PhaseShuntConnectionKind

The configuration of phase connections for a single terminal device such as a load or capacitor.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|D
|
Delta connection.


|G
|
Ground connection; use when explicit connection to ground needs to be expressed in combination with the phase code, such as for electrical wire/cable or for meters.


|I
|
Independent winding, for single-phase connections.


|Y
|
Wye connection.


|Yn
|
Wye, with neutral brought out for grounding.

|===
[[merged_ontology-RegulatingControlModeKind]]
==== RegulatingControlModeKind

The kind of regulation model. For example regulating voltage, reactive power, active power, etc.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|activePower
|
Active power is specified.


|admittance
|
Admittance is specified.


|currentFlow
|
Current flow is specified.


|powerFactor
|
Power factor is specified.


|reactivePower
|
Reactive power is specified.


|temperature
|
Control switches on/off based on the local temperature (i.e., a thermostat).


|timeScheduled
|
Control switches on/off by time of day. The times may change on the weekend, or in different seasons.


|voltage
|
Voltage is specified.

|===
[[merged_ontology-SinglePhaseKind]]
==== SinglePhaseKind

Enumeration of phase identifiers used to designate the specific phase of conducting equipment modelled as individual unbalanced phases.

Allows designation of specific phases for transmission and distribution equipment, circuits and loads.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|A
|
Phase A.


|B
|
Phase B.


|C
|
Phase C.


|N
|
Neutral.


|s1
|
Secondary phase 1.


|s2
|
Secondary phase 2.

|===
[[merged_ontology-WindGenUnitKind]]
==== WindGenUnitKind

Kind of wind generating unit.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|offshore
|
The wind generating unit is located offshore.


|onshore
|
The wind generating unit is located onshore.

|===
[[merged_ontology-WindingConnection]]
==== WindingConnection

Winding connection type.


[%header,width="100%",cols="25%,75%a"]
|===
|name |description

|A
|
Autotransformer common winding.


|D
|
Delta.


|I
|
Independent winding, for single-phase connections.


|Y
|
Wye.


|Yn
|
Wye, with neutral brought out for grounding.


|Z
|
ZigZag.


|Zn
|
ZigZag, with neutral brought out for grounding.

|===

=== Datatypes

[[merged_ontology-ActivePower]]
==== ActivePower

Product of RMS value of the voltage and the RMS value of the in-phase component of the current.


XSD type: float

[[merged_ontology-AngleDegrees]]
==== AngleDegrees

Measurement of angle in degrees.


XSD type: float

[[merged_ontology-ApparentPower]]
==== ApparentPower

Product of the RMS value of the voltage and the RMS value of the current.


XSD type: float

[[merged_ontology-Conductance]]
==== Conductance

Factor by which voltage must be multiplied to give corresponding power lost from a circuit. Real part of admittance.


XSD type: float

[[merged_ontology-CurrentFlow]]
==== CurrentFlow

Electrical current with sign convention: positive flow is out of the conducting equipment into the connectivity node. Can be both AC and DC.


XSD type: float

[[merged_ontology-Impedance]]
==== Impedance

Ratio of voltage to current.


XSD type: float

[[merged_ontology-KiloActivePower]]
==== KiloActivePower

Active power in kilowatts.


XSD type: float

[[merged_ontology-Length]]
==== Length

Unit of length. It shall be a positive value or zero.


XSD type: float

[[merged_ontology-PerCent]]
==== PerCent

Percentage on a defined base. For example, specify as 100 to indicate at the defined base.


XSD type: float

[[merged_ontology-Reactance]]
==== Reactance

Reactance (imaginary part of impedance), at rated frequency.


XSD type: float

[[merged_ontology-ReactancePerLength]]
==== ReactancePerLength

Reactance (imaginary part of impedance) per unit of length, at rated frequency.


XSD type: float

[[merged_ontology-ReactivePower]]
==== ReactivePower

Product of RMS value of the voltage and the RMS value of the quadrature component of the current.


XSD type: float

[[merged_ontology-RealEnergy]]
==== RealEnergy

Real electrical energy.


XSD type: float

[[merged_ontology-Resistance]]
==== Resistance

Resistance (real part of impedance).


XSD type: float

[[merged_ontology-ResistancePerLength]]
==== ResistancePerLength

Resistance (real part of impedance) per unit of length.


XSD type: float

[[merged_ontology-Seconds]]
==== Seconds

Time, in seconds.


XSD type: float

[[merged_ontology-Susceptance]]
==== Susceptance

Imaginary part of admittance.


XSD type: float

[[merged_ontology-SusceptancePerLength]]
==== SusceptancePerLength

Imaginary part of admittance per unit of length.


XSD type: float

[[merged_ontology-Temperature]]
==== Temperature

Value of temperature in degrees Celsius.


XSD type: float

[[merged_ontology-Voltage]]
==== Voltage

Electrical voltage, can be both AC and DC.


XSD type: float


=== Primitive Types

[[merged_ontology-Boolean]]
==== Boolean

A type with the value space "true" and "false".http://langdale.com.au/2005/UML#primitive

XSD type: boolean

[[merged_ontology-Float]]
==== Float

A floating point number. The range is unspecified and not limited.http://langdale.com.au/2005/UML#primitive

XSD type: float

[[merged_ontology-Integer]]
==== Integer

An integer number. The range is unspecified and not limited.http://langdale.com.au/2005/UML#primitive

XSD type: integer

[[merged_ontology-String]]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.http://langdale.com.au/2005/UML#primitive

XSD type: string


